### PR TITLE
Options fix

### PR DESCRIPTION
**Pull request by BlindGuyNW**
Add labels to all DialogOptionComponents. #1290.

### CODE REVIEW

**Comment by BlindGuyNW** [comment]
Accidental close due to user error. Please carry on :)

**Comment by sixlettervariables** [comment]
No worries! So the code looks good, but I'm trying to find a way I can verify this stuff works. I installed NVDA and cannot really figure out how to get it to "see" inside MM (which is perhaps the problem).

Are there tools you use that I should be using to review this work?

**Comment by BlindGuyNW** [comment]
Hey,

Okay, yeah. I forgot that you need to enable the Java ACcess Bridge in WINdows. If you go into the Java bin directory there’s a program called jabswitch.exe. I think the command line syntax is “jabswitch /enable.” If you enable the JAB NVDA should suddenly see inside MM and all the other related programs, possibly with a restart.

Hope it works :)
Zack.

**Comment by sixlettervariables** [comment]
I have it working now, thanks!

**Pull request merged**
