### PR TITLE
#5811 Some validation rules and illegal design quirk

### LINKED ISSUE #5811: Validation accepts Heavy Gauss Rifle with ICE
### Environment
MML from master branch

### Description
Units with an ICE rather than a nuclear engine can mount a heavy gauss rifle without being marked invalid, despite this being forbidden (TechManual p219).

Notably, the Gauss-Buster is a canonical unit with the Illegal Design quirk for violating this rule, but it passes validation. 

image

### PR DESCRIPTION
**Pull request by SJuliez**
- adds a few tests to unit validation
- adds a check for the Illegal Design quirk which will make validation pass even when there are errors; the heavy gameplay penalties of this quirk are not implemented currently
- adds missing quirks to some units of XTRO Caveat Emptor
- updates the mechview to show errors with a different header when the illegal design quirk is present
- removes a redundant override from the various TestXYZ classes

Fixes #5811 

image

### CODE REVIEW

**Review by HammerGS — APPROVED** [review]

**Comment by pavelbraginskiy** [comment]
As mentioned in https://github.com/MegaMek/megamek/issues/5811#issuecomment-2255731889, the RISC Hyper Laser is another piece of equipment that should require a nuclear engine. Could you add a check for that as well?

**Review by NickAragua — APPROVED** [review]
Do we have the horrific drawbacks that come with the Illegal Design quirk?

**Comment by pavelbraginskiy** [comment]
> Do we have the horrific drawbacks that come with the Illegal Design quirk?

> the heavy gameplay penalties of this quirk are not implemented currently

**Comment by SJuliez** [comment]
> As mentioned in [#5811 (comment)](https://github.com/MegaMek/megamek/issues/5811#issuecomment-2255731889), the RISC Hyper Laser is another piece of equipment that should require a nuclear engine. Could you add a check for that as well?
> 
> IO:AE p87

TestMech already contains a test for the RHL. I didn't try it out. I suppose you tried it and it validated?

**Comment by pavelbraginskiy** [comment]
> > As mentioned in [#5811 (comment)](https://github.com/MegaMek/megamek/issues/5811#issuecomment-2255731889), the RISC Hyper Laser is another piece of equipment that should require a nuclear engine. Could you add a check for that as well?
> > IO:AE p87
> 
> TestMech already contains a test for the RHL. I didn't try it out. I suppose you tried it and it validated?

I tried it with an ICE vehicle and MML said it was valid. Maybe it only checks it on mechs or something like that?

**Pull request merged**
