### PR TITLE
SPAs for air units

### PR DESCRIPTION
**Pull request by pheonixstorm**
Basic Golden Goose and Ground Hugger
Shaky Stick

Still working on getting th remainder of GG and GH finished as well as one or two other spas for air units.

### CODE REVIEW

**Comment by arlith** [comment]
Adding pending label, since this PR isn't ready to be merged yet.

**Comment by pheonixstorm** [comment]
@Akjosch  @arlith 
Any suggestions on how to work the double strike/strafe for ground hugger? I am testing the bomb scatter bonus for golden goose now and looking for some ideas to get the next up and running as soon as possible.

**Comment by arlith** [comment]
Where are the rules?

**Comment by pheonixstorm** [comment]
TW pg 243 and A Time of War Companion p64

**Comment by pheonixstorm** [comment]
Found a bug
The first is LRM/SRM smoke rounds should not scatter. There is nothing in TacOps or the errata that says they should. Found on p371 & 77 in the errata.

The second is the Altitude bombing scatter direction is wrong.

Once I am done testing the bombing changes I will start up a ticket for these and any others I might find

**Comment by Akjosch** [comment]
I'm not that versed in the specific code to offer much advice, I'm afraid. My general advice would be to make an event for the "bomb scattered" part and let the event handlers modify where it scattered *to*. Register an event handler for the "Golden Goose" ability, in it just check if `event.getPilot()` has the ability, and if so lower the scatter distance by 2 (to the minimum of 0).

**Comment by Akjosch** [comment]
I sit down and wrote an example `BombScatteredEvent`. It's mostly just a bunch of getters and setters and an interface to deal with those events.

```
public class BombScatteredEvent extends EventObject {
	private static final long serialVersionUID = 731664314617019539L;
	
	private final Entity attacker;
	private final Coords target;
	private Coords scatterTarget;
	private Coords explicitTarget;
	private int direction;
	private int amount;
	
	public BombScatteredEvent(BombAttackHandler source, Entity attacker, Coords target, int direction, int amount) {
		super(source);
		this.attacker = Objects.requireNonNull(attacker);
		this.target = Objects.requireNonNull(target);
		this.direction = direction;
		this.amount = amount;
		updateScatterTarget();
		this.explicitTarget = null;
	}
	
	private void updateScatterTarget() {
		scatterTarget = target.translated(direction, amount);
	}
	
	public Entity getAttacker() {
		return attacker;
	}
	
	public Coords getTarget() {
		return target;
	}
	
	public void setScatterDirection(int direction) {
		direction = direction % 6;
		if(direction < 0) {
			direction += 6;
		}
		if(this.direction != direction) {
			this.direction = direction;
			updateScatterTarget();
		}
	}
	
	public int getScatterDirection() {
		return direction;
	}
	
	public void setScatterAmount(int amount) {
		if(this.amount != amount) {
			this.amount = amount;
			updateScatterTarget();
		}
	}
	
	public int getScatterAmount() {
		return amount;
	}
	
	// explicit target handling, overrides scatterDirection and scatterAmount
	public void setExplicitTarget(Coords target) {
		this.explicitTarget = Objects.requireNonNull(target);
	}
	
	public void resetExplicitTarget() {
		this.explicitTarget = null;
	}
	
	public boolean hasExplicitTarget() {
		return (null != explicitTarget);
	}
	
	// Target after all the event handlers so far were done
	public Coords getScatterTarget() {
		return hasExplicitTarget() ? explicitTarget : scatterTarget;
	}
	
	// Fire events
	public void fireEvent(List<BombScatteredEventHandler> handlers) {
		if(null == handlers) {
			return;
		}
		for(BombScatteredEventHandler handler : handlers) {
			handler.handleBombScatteredEvent(this);
		}
	}
	
	public static interface BombScatteredEventHandler {
		void handleBombScatteredEvent(BombScatteredEvent event);
	}
}
```

Note: This is just an example. I'm not sure if there is anything missing which would be required for other SPAs, planetary conditions, optional rules and whatnot.

`BombAttackHandler` will have to get a list of `BombScatteredEventHandler`s passed along (or queried from the game). It can then construct the event once it's clear that the bombs will scatter:

    BombScatteredEvent bsEvent = new BombScatteredEvent(this, ae, coords, Compute.d6(1) - 1, -typeModifiedToHit.getMoS());

And then let the handlers deal with it:

    bsEvent.fireEvent(bsEventHandlers);

And finally query the coordinates:

    drop = bsEvent.getScatterTarget();

The "Golden Goose" SPA will have to implement `BombScatteredEventHandler`, for example like this:

		@Override
		public void handleBombScatteredEvent(BombScatteredEvent event) {
			if(event.getAttacker().isAirborne() && /* however you check if it has the SPA */) {
				event.setScatterAmount(Math.max(event.getScatterAmount() - 2, 0));
			}
		}

And that's it. Some data, one very short event handler, can deal with multiple influences on how stuff scatters at once.

**Comment by pheonixstorm** [comment]
@Akjosch 
I'm not really after bomb scatter. The code for golden goose is already in place. What I **AM** after to finish this PR is how to work a double strike (w/o heat on the second attack) and how to break a strafe from 1 set of 5 hexes to 1 set of 5 OR 2 sets of 3. That is for the ground hugger SPA.

I have been looking into melee master for ideas on how to set it up for the strike, but the overall application eludes me. If I was far more familar with the code and java I think I would have a much easier time. But.. I do so prefer C/C++...

**Comment by Akjosch** [comment]
My solution for "Ground Hugger" would run roughly along the same lines, only make target designation a bit more flexible in general and hook some new event into heat generation, allowing to modify it more easily (pass the attack details and the heat generated into the event, let event handlers modify the heat, read back from the processed event - same deal as what my BombScatteredEvent does to the scatter target).

**Comment by pheonixstorm** [comment]
Bomb scatter is working. This is how it shows up:
`Weapons fire for Rapier RPR-200 (test)
    Altiude Bomb at Hex: 3237 (Bomb); needs 8, rolls 7 : misses the intended hex 3237.
    HE Bomb scatters to hex 3237!
Gienah-Durapaq Elite Land Train (Tractor) Series 3 (Princess) hit for 10 damage.
        Gienah-Durapaq Elite Land Train (Tractor) Series 3 (Princess) takes 5 damage to FR.
            27 Armor remaining.
        Gienah-Durapaq Elite Land Train (Tractor) Series 3 (Princess) takes 5 damage to FR.
            22 Armor remaining.
    Altiude Bomb at Hex: 3237 (Bomb); needs 8, rolls 7 : misses the intended hex 3237.
    HE Bomb scatters to hex 3237!
Gienah-Durapaq Elite Land Train (Tractor) Series 3 (Princess) hit for 10 damage.
        Gienah-Durapaq Elite Land Train (Tractor) Series 3 (Princess) takes 5 damage to FR.
            17 Armor remaining.
            Chance for motive system damage. Roll is 9; (w/ +3 bonus)
             Moderate damage, +2 to driving skill rolls, -1 MP.
        Gienah-Durapaq Elite Land Train (Tractor) Series 3 (Princess) takes 5 damage to FRRS.
            20 Armor remaining.
            Chance for motive system damage. Roll is 10; (w/ +3 bonus)
             Heavy damage, +3 to driving skill rolls, 1/2 MP.

    Altiude Bomb at Hex: 3337 (Bomb); needs 8, rolls 5 : misses the intended hex 3337.
    HE Bomb scatters to hex 3436!
    Altiude Bomb at Hex: 3337 (Bomb); needs 8, rolls 9 : hits the intended hex 3337.
    HE Bomb incoming!
Gienah-Durapaq Elite Land Train (Tractor) Series 3 #2 (Princess) hit for 10 damage.
        Gienah-Durapaq Elite Land Train (Tractor) Series 3 #2 (Princess) takes 5 damage to FR.
            27 Armor remaining.
        Gienah-Durapaq Elite Land Train (Tractor) Series 3 #2 (Princess) takes 5 damage to FR.
            22 Armor remaining.
`

**Comment by pheonixstorm** [comment]
This can be merged w/o the advanced double strike/strafe. It might be awhile before I can get it worked out. Your call but I don't see holding up the rest of this for it.

**Comment by arlith** [comment]
The strafing effects for ground hugger wouldn't be hard to implement.  All you need to do is update `FiringDisplay.validStrafingCoord`.

For the ability to make two strikes, it's a bit more complicated.  I can't see how bits and pieces might work, but I can't really give you helpful advice without sitting down and working on it.

**Comment by pheonixstorm** [comment]
I'm not sure if I looked at that earlier but I know that the double strafe uses 2 strafing lines of 3 hexes each or the default 5 hex line.

The double strike I think will require a means to target two separate entities. Everything I need is probably already there I just need to find it and figure out how to put it together.

**Comment by arlith** [comment]
I don't think I'd allow one attack to target two units.  Basically, the way it works is that there are `AttackAction`s, and all of the weapon attacks sublcass `AttackAction`.  The way strafing works is the UI will queue up `AttackAction`s somewhat different than for normal attacks.

Although, on the other hand, the strafing already makes the UI display targeting numbers for two separate units, so it may be easier to allow two targets.

**Comment by pheonixstorm** [comment]
For the double strike it's two strike attacks. It sorta works like melee master which is why I was looking into that portion of the code initially to try and figure this out. Once, or if, I get the proper attack code sorted out I will then need to figure out how to block the heat effects from the second strike as the rules state that the second attacks hear is ignored. The other issue (which I can pull from the strafing code) is that the second attack cannot use ammo dependent weapons.

All of these issues are why I brought up the fact that this can be merged as is. It's up to you though. I can try to complete this but I don't know how long it will take. Maybe a few days, or could be a few months.

As it stands there are easier items on my list I can get done plus I need to rework the terrain master PR as it is in conflicting state and I want to hold off on the Nightwalker and Drag Racer options for now.

**Comment by pheonixstorm** [comment]
With all the recent change this branch needs to be rewritten. I am going to split out Shaky Stick since it is 100% complete and probably split the last two up as well considering the size of them.

**Pull request closed without merging**
