### PR TITLE
Remove dependency on TinyXML

### PR DESCRIPTION
**Pull request by nderwin**
This pull request converts the following remaining areas that were using TinyXML for unmarshalling and marshalling XML files to using the Java Architecture for XML Binding (JAXB)

- Map settings 
- Game options (mmconf/gameoptions.xml)
- Client preferences (clientsettings.xml)
- Entity verifier configuration (UnitVerifierOptions.xml)
- The Drawing Board mech files (data/mechfiles/.../*.xml)

Unit tests have been added for each to test that the files can be marshalled and unmarshalled as expected.  The format of existing XML files for these areas is **unchanged** - all of these conversions are intended to be backwards compatible with existing files.

Additionally, the build script was modified to copy over test resources to sit along side the compiled test classes so they would function.

Minor code updates appear as well, where the impact was minimal.

A bug was also fixed with the Entity Verifier.  The original code was looking for a tag named "tragcomp" in the configuration file.  This has been fixed to "targcomp", so more entities may now fail the verifier.

Files removed with the PR are

- megamek/lib/TinyXML.jar (no longer needed)
- megamek/lib/tinyXML07-src.zip (no longer needed)
- megamek/src/megamek/common/XMLStreamParser.java (deprecated and not used)
- megamek/src/megamek/test/TinyXMLTest.java (no longer needed)

### CODE REVIEW

**Comment by pheonixstorm** [comment]
Does this affect MekHQ in any way?

**Comment by nderwin** [comment]
Ah... That's a great question.  I'll clone the MekHQ (and MegaMekLab) repos a little later and investigate.

**Comment by nderwin** [comment]
@pheonixstorm So, the answer to your question is "yes".  I've added PRs in the MekHQ and MegaMekLab project for the affected calls.

**Comment by arlith** [comment]
It looks like there might have been a find/replace mistake in Server.  There are some comments that have "build" replaced with "getInstance".  Otherwise, I've looked through the code and it looks reasonable.  There are still some things I want to do before merging this, but if you could fix those comment changes, it'd be appreciated.

**Comment by nderwin** [comment]
@arlith Yes;  I had fixed that in a couple of other places, but missed Server.  I'll take care of that this evening.

**Comment by Dylan-M** [comment]
This pull request's acceptance has added a lot of "This constructor <insert name> is never used locally" warnings. I would like you to clean these up please. And don't just suppress them either. Eclipse is showing me 14 of them:

Description	Resource	Path	Location	Type
The constructor GameOptions.GameOptionsXML() is never used locally	GameOptions.java	/MegaMek/megamek/src/megamek/common/options	line 449	Java Problem
The constructor PreferenceManager.Settings() is never used locally	PreferenceManager.java	/MegaMek/megamek/src/megamek/common/preference	line 171	Java Problem
The constructor PreferenceManager.Store() is never used locally	PreferenceManager.java	/MegaMek/megamek/src/megamek/common/preference	line 199	Java Problem
The constructor PreferenceManager.XmlProperty() is never used locally	PreferenceManager.java	/MegaMek/megamek/src/megamek/common/preference	line 233	Java Problem
The constructor TdbFile.BasicInformation() is never used locally	TdbFile.java	/MegaMek/megamek/src/megamek/common/loaders	line 521	Java Problem
The constructor TdbFile.Creator() is never used locally	TdbFile.java	/MegaMek/megamek/src/megamek/common/loaders	line 482	Java Problem
The constructor TdbFile.CriticalDefinitions() is never used locally	TdbFile.java	/MegaMek/megamek/src/megamek/common/loaders	line 674	Java Problem
The constructor TdbFile.Engine() is never used locally	TdbFile.java	/MegaMek/megamek/src/megamek/common/loaders	line 626	Java Problem
The constructor TdbFile.HeatSink() is never used locally	TdbFile.java	/MegaMek/megamek/src/megamek/common/loaders	line 605	Java Problem
The constructor TdbFile.MountedItem() is never used locally	TdbFile.java	/MegaMek/megamek/src/megamek/common/loaders	line 661	Java Problem
The constructor TdbFile.MovementModifier() is never used locally	TdbFile.java	/MegaMek/megamek/src/megamek/common/loaders	line 589	Java Problem
The constructor TdbFile.Structure() is never used locally	TdbFile.java	/MegaMek/megamek/src/megamek/common/loaders	line 553	Java Problem
The constructor TdbFile.Technology() is never used locally	TdbFile.java	/MegaMek/megamek/src/megamek/common/loaders	line 575	Java Problem
The method getPreferenceStore() from the type PreferenceManager.Store is never used locally	PreferenceManager.java	/MegaMek/megamek/src/megamek/common/preference	line 202	Java Problem

Thanks. I look forward to the pull request that fixes this.

**Pull request merged**
