### PR TITLE
Fixes double blind ghost sprite

### LINKED ISSUE #5951: Megamek via MekHQ - 0.50.0 Snapshot CI1597 Nightly: Double blind with 'fade out unseen units' option can create duplicates on the board.
### Environment
Version: MekHQ-0.50.0-SNAPSHOT - CI1597 Nightly - Megamek launched via MekHQ
OS: Win11
Java: 17

### Description
image

This is the first time I've seen this bug.

When deploying double-blind units, having lost deployment initiative, I placed down my forces. The Griffin with the "Spike" callsign was placed visible to Princess.

This created two versions on the board - an unclickable 'faded out' version of the Griffin, and a 'live' actual version that is interactable.

The faded out "SPIKE" mek cannot be interacted with at all but remains on the board.

### Files
Megamek game save:
[DoubleBlindIssue.sav.gz](https://github.com/user-attachments/files/16783375/DoubleBlindIssue.sav.gz)

MekHQ campaign save pre-battle to set it off from the start:
[The Nova Dragoons30000630.cpnx.gz](https://github.com/user-attachments/files/16783374/The.Nova.Dragoons30000630.cpnx.gz)

### PR DESCRIPTION
**Pull request by HoneySkull**
Fixes #5951 - When a player selects next unit, or a different unit from the unit list during the deployment phase, the units position is set to null (the correct thing to do here), which resulted in the enity sprite list being cleaned up before the backing sprites were removed effectively orphaning the sprite reference in the `overTerrainSprites` collection.

```mermaid
sequenceDiagram
    actor player
    player ->> DeploymentDisplay: actionPerformed "Next Unit"
    DeploymentDisplay ->> Entity: setPosition(null)
    DeploymentDisplay ->> +BoardView: redrawEntity()
    opt Entity position is null
        BoardView ->> +EntitySprites: remove Sprite
        note over BoardView, EntitySprites: Current sprite is no longer in <br/> EntitySprites collection
    
    end
    BoardView ->> BoardView: removeSprites(EntitySprites)
    note over BoardView: when position was null, removeSprites <br/> does nothing and sprite is orphaned.
    BoardView -->> -DeploymentDisplay: return
```

To fix this, I moved the calls to clear out the backing sprite collections before the enitity sprite collection removes them.
> [!NOTE]
> The methods to maintain the backing sprite lists, `overTerrainSprites` and `behindTerrainHexSprites` require a reference to the sprites in order to remove them.

```mermaid
sequenceDiagram
    actor player
    player ->> DeploymentDisplay: actionPerformed "Next Unit"
    DeploymentDisplay ->> Entity: setPosition(null)
    DeploymentDisplay ->> +BoardView: redrawEntity()
    BoardView ->> BoardView: removeSprites(EntitySprites)
    opt Entity position is null
        BoardView ->> +EntitySprites: remove Sprite
        note over BoardView, EntitySprites: Current sprite is no longer in <br/> EntitySprites collection
    
    end
    BoardView ->> BoardView: addSprites(newSprites)
    BoardView -->> -DeploymentDisplay: return
```

> [!NOTE]
> Also removed unused `redrawEntity(Entity)` as it was never used and cleaned up the unused parameter in `redrawEntity(Entity, Entity)`.

### CODE REVIEW

**Comment by HammerGS** [comment]
I have to say that diagram is super cool

**Comment by HoneySkull** [comment]
This is all it is in Mermaid MD:

```
sequenceDiagram
    actor player
    player ->> DeploymentDisplay: actionPerformed "Next Unit"
    DeploymentDisplay ->> Entity: setPosition(null)
    DeploymentDisplay ->> +BoardView: redrawEntity()
    BoardView ->> BoardView: removeSprites(EntitySprites)
    opt Entity position is null
        BoardView ->> +EntitySprites: remove Sprite
        note over BoardView, EntitySprites: Current sprite is no longer in <br/> EntitySprites collection
    
    end
    BoardView ->> BoardView: addSprites(newSprites)
    BoardView -->> -DeploymentDisplay: return
```

**Comment by HammerGS** [comment]
> This is all it is in Mermaid MD:
> 
> ```
> sequenceDiagram
>     actor player
>     player ->> DeploymentDisplay: actionPerformed "Next Unit"
>     DeploymentDisplay ->> Entity: setPosition(null)
>     DeploymentDisplay ->> +BoardView: redrawEntity()
>     BoardView ->> BoardView: removeSprites(EntitySprites)
>     opt Entity position is null
>         BoardView ->> +EntitySprites: remove Sprite
>         note over BoardView, EntitySprites: Current sprite is no longer in <br/> EntitySprites collection
>     
>     end
>     BoardView ->> BoardView: addSprites(newSprites)
>     BoardView -->> -DeploymentDisplay: return
> ```

Do you make the sequence or does something make it for you?

**Comment by HoneySkull** [comment]
I hand edited the mermaid diagram text here, but I've seen people generate them with Copilot.

**Review by Sleet01 — APPROVED** [review]
LGTM!
Props for net removing code!

**Pull request merged**
