### PR TITLE
Tileset Clean-up & Completion

### PR DESCRIPTION
**Pull request by BLOODWOLF333**
Assembled the tilesets fully, using the images already inside MM and matching them with the respective tileset.  Only added new images for the LargeTexture.tileset which was largely incomplete and fiddled with a few images for my tileset.

### CODE REVIEW

**Comment by BLOODWOLF333** [comment]
Atmospheric [no theme]
Only changes were additions of the snow and jungle themes and making roads draw over all terrain.
nothemeatmospheric

Bloodwolf [no theme]
nothemebw

Classic [no theme]
Classic is heavy on the use of base images for terrain where as all other tilesets use supers.  Which causes problems for this outdated tileset with not having images for the classic theme woods in swamp hexes and some others.  New images would need to be created and right now I am just assembling them all and doubt this set gets very much use.
nothemeclassic

Hq_atmospheric [no theme]
Use of animated water and higher res images for terrain
nothemehq_atmospheric

Hq_isometric [no theme]
Same as hq_atmospheric but with iso trees
nothemehq_isometric

Isometric [no theme]
same as atmospheric but with iso trees
nothemeisometric

Largetexture [no theme]
Largetexture uses large 800x600 images in place of a majority of the base images for base-terrain with hq_atmospheric super images for all other terrain types.
nothemelargetexture

Atmospheric [grass]
grassatmospheric

Atmospheric [jungle]
jungleatmospheric

Atmospheric [lunar]
The lunar theme is the exact same for all tilesets except for largetexture and Bloodwolf. 
lunaratmospheric

Atmospheric [mars]
The mars theme is the exact same for all tilesets except for largetexture and Bloodwolf.
marsatmospheric

Atmospheric [snow]
snowatmospheric

Atmospheric [volcano]
volcanoatmospheric

Bloodwolf [grass]
grassbw

Bloodwolf [jungle]
junglebw

Bloodwolf [snow]
snowbw

Classic [grass]
grassclassic

Classic [jungle]
jungleclassic

Classic [snow]
snowclassic

Classic [volcano]
volcanoclassic

Hq_atmospheric [grass]
grasshq_atmospheric

Hq_atmospheric [jungle]
junglehq_atmospheric

Hq_atmospheric [snow]
snowhq_atmospheric

Hq_atmospheric [volcano]
volcanohq_atmospheric

Hq_isometric [grass]
grasshq_isometric

Hq_isometric [jungle]
junglehq_isometric

Hq_isometric [snow]
snowhq_isometric

Hq_isometric [volcano]
volcanohq_isometric

Isometric [grass]
grassisometric

Isometric [jungle]
jungleisometric

Isometric [snow]
snowisometric

Isometric [volcano]
volcanoisometric

Largetexture [grass]
grasslargetexture

Largetexture [jungle]
junglelargetexture

Largetexture [lunar]
lunarlargetexture

Largetexture [mars]
marslargetexture

Largetexture [snow]
snowlargetexture

Largetexture [volcano]
volcanolargetexture

Largetexture [space]
space

**Comment by pheonixstorm** [comment]
For something like this there is no reason to merge whatever changes happen in MM/master into your branch since these are new and don't conflict with what is already in MM.

**Comment by BLOODWOLF333** [comment]
(doesnt know what he is doing yet and is learning at Arlith's request) I thought I needed to keep my branch up to date with the master?

**Comment by arlith** [comment]
I believe the GitHub Desktop directions instruct you to "sync", or at least that's what @BLOODWOLF333 told me when I told him the same thing.  It just means there will be additional merge commits, which isn't that big of a deal.

**Comment by pheonixstorm** [comment]
sync doesn't merge though, that is still something you have to do on your own.

As for keeping it up to date. keep your master up to date by merging and syncing but for all projects create a new branch from your master. This way you have a clean master and only have to do a merge if your PR shows a conflict that needs to be fixed. I can provide pictures and tips for it as I still have GH Desktop installed.

**Pull request merged**
