### PR TITLE
Fun with ratings

### PR DESCRIPTION
**Pull request by repligator**
Adds the word "Equipment" in front of the equipment ratings in the Formation Builder, RAT Generator, ETC.

PS. I need to delete the revision file after posting the pull request because I can't figure out how to do it before...

### CODE REVIEW

**Review by repligator — COMMENTED** [review]
Hopefully deleted now

**Comment by IllianiCBT** [comment]
Looks like this has picked up conflicts relating to the `mm-revision.txt` file if you can get it resolved I can go ahead and merge this in.

**Comment by repligator** [comment]
I don't have write access to the repository. If you click on "View Reviewed Changes" it _should_ let you approve my recommendation to delete it.

**Comment by IllianiCBT** [comment]
I'll pass it up the chain. I want confirmation from Juli of exactly what we should be doing with this before I confirm it's deletion. I'm fairly certain delete is the right thing, but if I merge the delete it gets deleted for everyone.

**Comment by SJuliez** [comment]
@repligator sorry for this confusion. the mm-revision file should not be deleted as part of the PR. I have since added it to .gitignore so git should no longer try to make it part of a PR. Could you try a) syncing your fork and b) fetching (updating) in your IDE and merging in the latest master into this branch. Then it should actually no longer be a problem. If all is updated on your side, I'll try to deal with any remaining problems.

**Pull request closed without merging**
