### PR TITLE
Bugfixes for #175 #127 #74 #43 and #187

### PR DESCRIPTION
**Pull request by pheonixstorm**
Ready for review and merge.

I will probably post a few more terrain questions on the forum once I put together a list of things I am puzzled/curious about.

### CODE REVIEW

**Comment by pheonixstorm** [comment]
@arlith this is ready for you to review now

**Comment by pheonixstorm** [comment]
In the process of adding a fix for #187 and then this will be ready to go. Again.

**Comment by pheonixstorm** [comment]
That should be my final commit for this PR

**Comment by arlith** [comment]
In the future, if you use the proper words in your commit messages, I believe perging the PR will correctly close issues: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by pheonixstorm** [comment]
Did not know about that. Thanks for the link arlith.

**Comment by pheonixstorm** [comment]
I just read over it and I won't be able to unless I have push access to this repo.

> Closing an issue in a different repository
To close an issue in another repository, use the username/repository#issue_number syntax, as described in "Autolinked references and URLs".
For example, including Closes example_user/example_repo#76 will close the referenced issue in that repository, provided you have push access to that repository.

**Pull request merged**
