### PR TITLE
Fix #1679 Vertical Lift Off PSR incorrectly applying crater modifier

### LINKED ISSUE #1679: Vertical Lift Off PSR incorrectly applying crater modifier
### Environment
- MegaMek-0.47.4
- Standalone
- Linux
- openjdk version 1.8.0_232
- There's nothing relevant in megameklog.txt

### Description
When performing a "Vertical Lift Off" the resulting PSR is incorrectly having the +3 "Taking off from Crater" modifier applied. This applies to ASFs, LAMs in ASF mode, but NOT to spheroid dropships.

Looking at  megamek.common.IAero.java 366-388, "a crater" is defined as a hex where the level of all surrounding hexes is greater than what we are sitting on.

### Files
Crater_Takeoff

Crater_Takeoff_Dropship

### PR DESCRIPTION
**Pull request by RAldrich**
Make crater check logic include the Entity's current hex, to support single hex Entities (e.g. ASFs)

#1679

### CODE REVIEW

**Comment by RAldrich** [comment]
This was manually tested using both an ASF and a spheroid dropship in both flat terrain and using the craters on the Moonscape1 map. Everything works as expected. I didn't bother optimizing the dropship check, it redundantly checks that the area under the dropship footprint is flat, but that seems fairly harmless.

**Comment by RAldrich** [comment]
> Could be simplified by retaining the original line and your `positions.add(pos)` (omitting the addAll)

True! Is that worth posting an update for? (Also, it looks like I don't have permissions to manually link this to the issue it's fixing - not sure why it didn't link automatically.)

And just because it's not documented, what's the process for merging? I assume a maintainer will pull it in when preparing to compile the next dev release?

**Comment by NickAragua** [comment]
Yeah, go ahead and push the update. GitHub should update the pull request if you push from the same branch. Once we "pass" the code review, one of the devs will merge the PR and close the associated issue.

**Comment by RAldrich** [comment]
> Yeah, go ahead and push the update. GitHub should update the pull request if you push from the same branch. Once we "pass" the code review, one of the devs will merge the PR and close the associated issue.

Pushed! Thanks for the guidance!

**Pull request merged**
