### PR TITLE
Adding runway overlays (fluff:14:*)

### PR DESCRIPTION
**Pull request by Akjosch**
Simple white numeric markings for runways, "36" (north), "06", "12", "18" (south), "24" and "30", with corresponding R(ight), C(enter) and L(eft) variants. Also middle line and end-of-runway markings in the three possible orientations.

All are under "fluff:14:(0-29)" and made as simple overlays; though they work best on something grey, like pavement or lunar terrain.

bt_runway

### CODE REVIEW

**Comment by arlith** [comment]
That looks neat.

I have a feeling like the existence of these fluff images will end up becoming somewhat of a secret.  I'm not sure if there's a good way to indicate that certain fluff options are available besides having maps that utilize them.  This has little to do with your pull request, and is more a comment on an issue present in MM.

**Comment by Akjosch** [comment]
Well, I tried to look through the files named after something like "spaceport" and "airport" to see if I could update those maps, but in all I found (`buildings/dropport*` and `unofficial/DarkISI/Flughafen*`), it wasn't very clear which parts are supposed to be runways, if any.

**Comment by MartinSojka** [comment]
@djmbm The thing is, I don't use the other tilesets, so I simply don't know if it would fit their theme or intended usage. Feel free to make your own pull request with that though, I won't touch them for now.

**Comment by Akjosch** [comment]
@djmbm The thing is, I don't use the other tilesets, so I simply don't know if it would fit their theme or intended usage. Feel free to make your own pull request with that though, I won't touch them for now.

(As a side note, I hate juggling between multiple account on GitHub, it's always a hassle. Sorry about any spam I will cause.)

**Comment by djmbm** [comment]
hahaha, I don't bother to fix mine. This is my work account, but it's @Dylan-M. My comment was more of a note that it needs done, and a slight dig at @arlith for not doing it when he merged the pull.

**Pull request merged**
