### PR TITLE
Allow Starting Height to VTOL Infantry/Battle Armor 

### PR DESCRIPTION
**Pull request by binaryspica**
Resolving #1468. Also allows VTOL Infantry to set the starting height.

Also I need to have a question: How high they can ascend? I have checked Total Warfare but there is nothing so I set the maximum height as normal VTOLs, but is it correct?

### CODE REVIEW

**Comment by binaryspica** [comment]
> The rules for VTOL movement (TW, p. 54) say that other units that share the VTOL movement mode use the same rules. So there is no need to distinguish between VTOL vehicles and infantry. The check for isVTOL should just check for movement mode and apply to all VTOL units.
> I don't know where the maximum of 50 comes from. TW says the maximum elevation for a VTOL is 500.

Will MegaMek support that much elevation? If so then there is no problem to change it, though.

**Comment by neoancient** [comment]
I don't know of any reason it wouldn't, though I don't see a good reason to go that high. An elevation of 50 would put you out of weapons range. Let's just leave it alone and focus on one issue.

**Comment by binaryspica** [comment]
Anyway thanks for the reference. Well, then what would be better, leave its maximum to 50 or expand it to 500 as rules says?

**Comment by neoancient** [comment]
Leave it alone and just deal with the issue of setting starting height for VTOL BA and conventional infantry.

**Comment by binaryspica** [comment]
Yes. Please note me if I miss anything else.

**Comment by binaryspica** [comment]
Is there any problem? I thought it seems good to go....

**Comment by HammerGS** [comment]
I still show requested changes, and right now lots of the devs are swamped.

**Comment by binaryspica** [comment]
The requested change was about maximum height but I thought it was good to leave it to be. Was I misunderstood that?

**Comment by NickAragua** [comment]
Right, I believe neo wanted you to adjust the logic so that all units with VTOL movement type behave identically.

**Comment by neoancient** [comment]
Right now they do behave identically. There's no need to track that with three separate variables that have the same value.

**Comment by binaryspica** [comment]
Got it. Well, is it possible to set the default height other than 0?

**Pull request merged**
