### PR TITLE
Implement repeating TSEMPs

### PR DESCRIPTION
**Pull request by Saklad5**
Repeating TSEMPs, as the name implies, can fire every turn.

Like any self-respecting RISC project, they also explode: in this case, on a roll of 2.

### CODE REVIEW

**Comment by Saklad5** [comment]
Closes https://github.com/MegaMek/megamek/issues/3813

**Comment by SJuliez** [comment]
Heya, @Saklad5 the code looks alright. Have you given this a test run by setting the roll to 2?

**Comment by Saklad5** [comment]
> Heya, @Saklad5 the code looks alright. Have you given this a test run by setting the roll to 2?

Not yet. Could you explain how to do so?

**Comment by SJuliez** [comment]
I mean adding a line to the code that makes sure the roll happens to be 2 (e.g. just before the check, or commenting out the check for testing, I mean you can do without but might have to shoot a lot to get it to explode); then starting a game with a unit wielding said TSEMP and seeing if it explodes in a satisfying way and gives a fitting report message and the unit behaves the round after like it should (not being able to fire the TSEMP again and so on)

**Comment by NickAragua** [comment]
@Saklad5 did you wind up running that test to get it to explode?

**Comment by Saklad5** [comment]
@NickAragua 
image

It worked fine, though it turned out there was an issue with the downtime skip. I fixed that, so I'll vouch for this being good to go.

**Review by SJuliez — APPROVED** [review]

**Pull request merged**
