### PR TITLE
Better default link color, add link color to advanced prefs

### PR DESCRIPTION
**Pull request by pakfront**
Resolves https://github.com/MegaMek/megamek/issues/3783
- makes default report link color more readable over light or dark background
- adds report link color to advanced options
- adds heat scale colors to advanced options

### CODE REVIEW

**Comment by kernhe** [comment]
Just tested it. Now links are readable but they are simply blue and ignore the  gtk_color_scheme entry for link_color.

Is there a way to configure the color, e.g. config file or MekHQ Options > colors?

**Comment by pakfront** [comment]
Yes, in advanced options there is an entry for Report color link, but ideally we'd be able to use the 'correct' settings from the theme. I'm not sure how to retrieve theme colors at runtime. I'll look into that.

**Comment by pakfront** [comment]
FYI, this is in Advanced options in MegaMek, not MekHQ.

**Comment by kernhe** [comment]
in megamek it works beautifully once you set the value in advanced options correct. Thanks!

... is there a way that HQ reuses the colors? (hint hint: https://github.com/MegaMek/mekhq/issues/3393)

**Review by NickAragua — APPROVED** [review]

**Pull request merged**
