### PR TITLE
Fixes Megamek Issue #3956 and Brings RAT up to date with '(Standard)'…

### PR DESCRIPTION
**Pull request by sldfgunslinger2766**
Fixes Megamek Issue #3956 and Brings RAT up to date with '(Standard)' and Trojan (Blockade Runner) (2780) unit files name changes.

### CODE REVIEW

**Comment by HammerGS** [comment]
Thanks for the fixes!

**Comment by sldfgunslinger2766** [comment]
No problem. Still not done yet though: while the (Standard) issue is fixed, the fix for issue #3956 still persists, Working on it now.

**Comment by sldfgunslinger2766** [comment]
Ok, I think the additional commits will resolve the issue

**Review by sldfgunslinger2766 — COMMENTED** [review]
This is good to committ

**Pull request merged**
