### PR TITLE
add report roll tooltip 

### PR DESCRIPTION
**Pull request by kuronekochomusuke**
- add report roll tooltip for piloting and gunnery skill checks
- add report roll tooltip to more of the reported rolls

image

image

image

image

image

### CODE REVIEW

**Comment by HammerGS** [comment]
Love this.

**Review by HoneySkull — COMMENTED** [review]
Design question:  Would it be beneficial to overload the `Report::add()` function to take a `Roll` parameter so that it can automatically `addDataWithToolTip(roll.getIntValue(), roll.getReport())` - in such a way that by default tooltips get generated?   It goes against Demitre's law a little because Report would need to know about Roll - but is a LOT of reporting code intermingled within the game logic -and tool tips are part of reporting.

**Comment by kuronekochomusuke** [comment]
I think it would make things a little cleaner in game logic parts of the code.  just need to see what impacts returning roll in some of the edge cases, but in general it seems an easy change.

**Review by SJuliez — APPROVED** [review]
Looks good to me

**Pull request merged**
