### PR TITLE
Fixes #4305 Environmental Specialist SPA not reducing penalties from high wind 

### LINKED ISSUE #4305: [0.49.12] Environmental Specialist SPA not reducing penalties from high wind
Bundled Megamek with MekHQ 0.49.12
Windows 10, Java Version: 11.0.13

Environmental Specialist, CamOps p74
'Storm' wind conditions TO: AR p34

For example, a hover unit with the Wind version of the SPA turning while flanking is not receiving any benefit:
image

A mech with the same SPA also has the full penalty turning while running on pavement:
image

Name: 'Test'

[test.sav.gz](https://github.com/MegaMek/megamek/files/11186667/test.sav.gz)

Rain and Snow appear to be working fine:
image

image

### PR DESCRIPTION
**Pull request by pheonixstorm**
Fixes the main issue in 4305 as well as a couple others I found.

### CODE REVIEW

**Review by NickAragua — COMMENTED** [review]
Looks fine on its own, but holy merge conflicts batman!

**Comment by pheonixstorm** [comment]
Yeah, someone slipped a pr in that changed the variable names for mp usage.

**Comment by SJuliez** [comment]
Sorry that was the MP calculation revamp for BV calculation

**Comment by pheonixstorm** [comment]
I think the fastest way to fix the merge conflicts will be to reset to an earlier commit and rebase the changes onto my branch, then reapply the last commit and repost. If that doesn't work then I will just start over.

**Pull request closed without merging**
