### PR TITLE
Adds DNI Cockpits to Celestials

### PR DESCRIPTION
**Pull request by repligator**
Adding DNI cockpits to Celestial mechs, partially implementing issue https://github.com/MegaMek/megamek/issues/5664. This is accomplished by adding a piece of equipment, DNICockpit, to the head that does not use a slot and can not be hit. It will display correctly in MML, but can't be manually added to a design. It's not a very pretty solution, but it (mostly) works, and can be easily removed later if DNI is switched to a quirk.

This should correctly calculate BV for all implants on lines 1206 to 1247 of megamek/src/megamek/common/battlevalue/BVCalculator.java. That being said, some of the features of the implants (for example Prototype VDNI) are still not implemented.

Also contains some totally unrelated fixes to Crab descriptions.

Tests:
All unit tests for MM passed or skipped, loaded units in MML, compared BV cost between implanted pilots and pilots with the equivalent natural level of skills in MM, fought short battle to confirm that some of the implants are functioning during battle.

P.S.
I need to remember to stop working in the master branch...

### CODE REVIEW

**Comment by IllianiCBT** [comment]
I would much prefer we come up with a permanent solution rather than a temporary fix. Do you think this is feasible, or is a temporary fix our best option without a significant amount of extra work?

**Comment by repligator** [comment]
The way I see it, a permanent solution would require everyone to agree on how implants (and implant based hardware on mechs) are going to be handled, and then implementing that into the code-base. I don't know if this would mean something like quirks, or SPAs, or something totally different; but it would require time and effort regardless.
This PR is a shamelessly hacky temporary fix until that time and effort is available. It was simple to implement, and should be even simpler to rip out once a better solution is found.
That being said, I have zero emotional attachment to this code. If you and others want to avoid a temporary solution, please feel free to reject/close the PR.

**Comment by repligator** [comment]
Closing. We can always implement it better, later.

**Comment by Thom293** [comment]
IMHO in a project of this type there is a utility in using a working but imperfect fix.  The perfect fix may never come, and if it does, it's a bonus.  Just my opinion.

**Comment by Saklad5** [comment]
The way I see it, modifications like VDNI are similar to an Armored Cockpit. Perhaps a similar approach could be used?

This also applies to Enhanced Imaging interfaces, Damage Interrupt Circuits, and SLDF Advanced Neurohelmets.

**Pull request closed without merging**
