### PR TITLE
allow fleeing at end of movement

### LINKED ISSUE #346: Ground Units able to flee if they have the MP
If a ground unit arrives at the map edge and still has remaining MP it should be allowed to flee immediately.

Perhaps as an unofficial option

### PR DESCRIPTION
**Pull request by kuronekochomusuke**
- allow fleeing at end of movement, if you have remaining movement
- check that unit made it to board edge before fleeing
- update report log, show direction  that the unit retreated

image
image
image
image
image

fixes #346

### CODE REVIEW

**Comment by IllianiCBT** [comment]
This is amazing!

**Comment by UlyssesSockdrawer** [comment]
Will this also check if the unit attempting to flee has at least one MP remaining to complete the move 'offboard'?

**Comment by kuronekochomusuke** [comment]
no, it just checks if you can make it to the edge of the board.

**Comment by HammerGS** [comment]
Let me know if this is ready to go?

**Comment by kuronekochomusuke** [comment]
yea, it is ready now

**Review by HammerGS — APPROVED** [review]
Limited testing and seems to work.

**Pull request merged**
