### PR TITLE
Fixed several incorrect armor cost values

### PR DESCRIPTION
**Pull request by pheonixstorm**
Not sure if there was an armor entry removed or if armor 18 was doubled but it caused several other armor prices to be off.

Also, should I go ahead and update the cost for prototype Ferro-Fibrous /Aluminum armors?

### CODE REVIEW

**Comment by HammerGS** [comment]
Go ahead and fix the prototype pricing and I'll merge this is.

**Comment by pheonixstorm** [comment]
Will do. Don't forget the Human TRO PR in HQ please :)

**Comment by pheonixstorm** [comment]
Didn't see a cost for Prototype Ferro-Aluminum , assuming same cost as Ferro-Fibrous Prototype. FA was listed under the rules/construction entry for Ferro-Fibrous Prototype.

Also, fixed cost for Prototype Endo Steel.

**Comment by HammerGS** [comment]
Thanks.

**Pull request merged**
