### PR TITLE
Initial work on ObjectInputFilter

### PR DESCRIPTION
**Pull request by rjhancock**
Initial work for SerialKiller replacement.

### CODE REVIEW

**Comment by repligator** [comment]
Got one, can't load saves. 
[megamek.log](https://github.com/user-attachments/files/16420497/megamek.log)
```
20:50:00,956 ERROR [megamek.server.Server] {AWT-EventQueue-0}
megamek.server.Server.loadGame(Server.java:930) - Unable to load file: /media/kaiser/Blau/Executables/Git/megamek/megamek/savegames/autosave.sav.gz
com.thoughtworks.xstream.security.ForbiddenClassException: megamek.common.Game
```

**Comment by rjhancock** [comment]
> Got one, can't load saves. [megamek.log](https://github.com/user-attachments/files/16420497/megamek.log)
> 
> ```
> 20:50:00,956 ERROR [megamek.server.Server] {AWT-EventQueue-0}
> megamek.server.Server.loadGame(Server.java:930) - Unable to load file: /media/kaiser/Blau/Executables/Git/megamek/megamek/savegames/autosave.sav.gz
> com.thoughtworks.xstream.security.ForbiddenClassException: megamek.common.Game
> ```

Fix is in the pipeline for all 3 repos. Tested locally.

**Comment by repligator** [comment]
Nothing interesting to report, but here are some logs.
[mekhq.log](https://github.com/user-attachments/files/16475389/mekhq.log)
[megamek.log](https://github.com/user-attachments/files/16475390/megamek.log)

**Comment by rjhancock** [comment]
Screenshot 2024-08-02 at 19 00 07

Wasn't expecting to see a MySQL error.... Saw no issues related to OIF however.

**Comment by mhjacks** [comment]
I appear to be unable to target with TAG in this savegame:
[savegame.sav.gz](https://github.com/user-attachments/files/16489118/savegame.sav.gz)

**Comment by rjhancock** [comment]
> I appear to be unable to target with TAG in this savegame: [savegame.sav.gz](https://github.com/user-attachments/files/16489118/savegame.sav.gz)
> 
> Log: [megamek.log](https://github.com/user-attachments/files/16489128/megamek.log)

The TAG issue is unrelated to the PR but did look through the logs and it had no issues related to this as well. Thank you for the log however.

**Pull request merged**
