### PR TITLE
Issue #207: Bot refuses to deploy because of NPE

### PR DESCRIPTION
**Pull request by dericpage**
We were already protecting against the current hex being null.  Added protection against the destination hex being null.

### CODE REVIEW

**Comment by arlith** [comment]
I came across this before, but I was reluctant to make this fix because I felt that the destination hex shouldn't be null.  I'm really interested in knowing what cases can lead to a destination hex being null.  I feel like there's probably an underlying problem that needs to be fixed there.

**Comment by dericpage** [comment]
Well, I don't think its valid for curHex to be NULL either.  If a unit is off-board, it's only available move (as I understand it) is to simply return to the board.  I would think there wouldn't be a need to check for a level difference in that case.  Also, Princess shouldn't be moving any off-board units anyway.

How it gets into this state is a good question because the ultimate destination hex is going to be the center of the board (as determined by IBoard.getCenter().  I don't see how that could possibly come back as null.  

However, it would seem that, somehow, ShortestPathFinder is creating paths that might go off-board somewhere along the way.  Unfortunately, I don't understand the path finder well enough to determine why.  Instead of just printing out the coordinates of the bad hex itself, maybe we should print out the entire path to get an idea of what ShortestPathFinder is thinking.

**Comment by arlith** [comment]
Yea, that might  be helpful.  I don't think the ShortestPathFinder ever changes the destination hex; my understanding was that the destination comes from the Princess code.  I was basically hunting this down before and I had the same conclusion; I don't see how you could get a null value being passed in.

One thought I had had is that, `BotClient.boardCenter` is static, and it's only set once (BotClient.java line 759).  If the `BotClient` instance is used for multiple games, that is, `BotClient.hasPathToCenter` is called for two different boards, the second board, if it's far larger than the first board, could have a center that's off the board of the first one, leading to a center `Coords` that could have a null `Hex`.  But, I think when I explored his before I dunno if it could happen in practice.  Regardless, it seems like the null check is probably not totally necessary, and you could always update boardCenter with the current board when `BotClient.hasPathToCenter` is called.

**Comment by dericpage** [comment]
I think I originally coded it as static to avoid doing the getCenter() calculation for dozens of meks (though looking at it, is a pretty simple operation).  I probably wasn't thinking about running multiple games without shutting down in between each.

I'll see about adding the full path to the error log in case of nulls and handling boardCenter better.

**Comment by arlith** [comment]
Sounds like a plan.

**Pull request merged**
