### PR TITLE
Issue 697 over verbose princess

### PR DESCRIPTION
**Pull request by dericpage**
Fix the issue of the princess verbosity setting not affecting the chat verbosity.

### CODE REVIEW

**Comment by arlith** [comment]
Is there something specific you want me to take a look at in this PR?  There's a ton of basically formatting type changes.

**Comment by dericpage** [comment]
You can see the relevant changes by looking at the first commit.

**Comment by arlith** [comment]
Yea, I should've thought of that.  Thanks.

In terms of concept, I think this is a good idea.  I glanced through the code and didn't notice any issues.

**Comment by BLOODWOLF333** [comment]
We need this

**Pull request merged**
