### PR TITLE
Removes additional space before file extension

### PR DESCRIPTION
**Pull request by rhubarbselleven**
A number of unit files had a space before the file extension. This commit removes that additional space.

### CODE REVIEW

**Comment by rhubarbselleven** [comment]
Is this the right place for PR's for you guys?

**Comment by Dylan-M** [comment]
We don't actually take PRs currently. We're still using patches. GitHub 
is not our primary repo, it is a backup repo.

**Comment by Dylan-M** [comment]
Just FYI, we're considering this pull request at this time. Thank you for your interest.

**Comment by Dylan-M** [comment]
Apparently these files were already fixed by an internal utility.

**Pull request closed without merging**
