### PR TITLE
3498: Adding Clanner Tracking to MegaMek

### PR DESCRIPTION
**Pull request by Windchild292**
This handles the bug raised in #3498, namely that any melee attacks are based on the 'Mech's tech base and not the pilot / commander's status.

### CODE REVIEW

**Review by HammerGS — CHANGES_REQUESTED** [review]
Withdrawn.

**Review by HammerGS — COMMENTED** [review]
Withdrawn

**Comment by HammerGS** [comment]
Based on the conversations on Discord. Please adjust the wording of any player facing text to "Clan Pilot". While the preference is to not have any reference in the code to the term "Clanner" that can stand.

**Comment by kernhe** [comment]
How can I help here?

**Comment by SJuliez** [comment]
Replaced by #5166

**Pull request closed without merging**
