### PR TITLE
Large space craft ammo

### PR DESCRIPTION
**Pull request by mkerensky**
+Enhancement: AR10 magazines have a base tonnage from the BLK file and can be loaded with alternate missile types in the lobby accordingly
+Enhancement: Added Peacemaker and Santa Anna nuclear munitions (S2S only) per IO rules. Can be loaded into appropriate capital missile launchers just like other alternate muntions, instead of the 'replace x killer whale warheads with nukes' option. 
+Enhancement: Ability to set number of shots in each aero ammo bin, even if you can't change the munition
+Enhancement: added functionality for Alamo (S2S) and ASEW bombs

### CODE REVIEW

**Comment by HammerGS** [comment]
Can suggest splitting this into a different PR's

- The Ammo one 
- The ASEW one (including bombs costs here)
- The Peacemaker/Alamo one

**Comment by neoancient** [comment]
Munitions flags are used to create variant ammo types from a single AmmoType entry in bulk, using all the same values except name, shots/ton, rules reference, and tech intro dates. It should not be used for AR10 ammos because they cannot be created by modifying those values. The flags field is sufficient to determine which type of missile it is, which is why it was set up that way. Furthermore, the `long` only has 64 bits, so trying to lshift a 1L more than 63 places leaves you with zero.

**Comment by neoancient** [comment]
Configurable ammo for large craft is implemented in the Large_craft branch, including capital missiles with nuclear warheads.

**Comment by mkerensky** [comment]
I'm keeping this open just in case I find I need something in it that I forgot about when I separated ASEW missiles and Nukes out. If they work when you merge large craft, this can be closed.

**Pull request closed without merging**
