### PR TITLE
SBF updates

### PR DESCRIPTION
**Pull request by SJuliez**
Some additions to SBF play. Minor impact on anything else.

### CODE REVIEW

**Comment by HammerGS** [comment]
Is this a draft?

**Comment by SJuliez** [comment]
Only in the sense that SBF is not complete :)

**Comment by repligator** [comment]
`map: AGoAC Maps\16x17 Desert 2.board` won't load on Linux. Loads fine when changed the `\` is changed to `/` . I realize that SBF is very much WIP, and multi OS support for parsing MMS files may not even be started yet, but I reckoned it was worth pointing out regardless.

**Comment by SJuliez** [comment]
@repligator Ah thanks, good point. I just hadnt thought about it when copying in the filename.

**Review by Sleet01 — APPROVED** [review]
Looking good!  This is really clean so far.

**Pull request merged**
