### PR TITLE
ERRATA: Removes PSR modifiers for lighting and move penalties with searchlights

### LINKED ISSUE #4090: ERRATA Changes for light conditions
This changed from TO second printing by errata v 3.03
 at the latest.

Old values +1/+2 for moonless and pitch black changed to +0/+0
TO:AR p34
PlanetaryConditions.java ln 420

I will have a pr up to correct this at some point.

### PR DESCRIPTION
**Pull request by pheonixstorm**
This brings PSR and movement penalties to the most recent copy of TO:AR 6th printing rules.
Fixes #4090

### CODE REVIEW

**Comment by SJuliez** [comment]
TO:AR p.56, pitch black does not seem to mention that a searchlight eliminates the MP penalty, does it?

**Comment by pheonixstorm** [comment]
I thought I had found a post about it but doing another search didn't turn up anything. I can remove it for now, but I'm certain I saw it somewhere.

**Comment by SJuliez** [comment]
Couldn't find anything either. I'd vote for removing it until clarified. @HammerGS Do you think searchlights should remove the MP penalty in pitch black? Rules don't say so but it's not clear to me why.

**Comment by pheonixstorm** [comment]
BMM doesn't include Pitch Black for some reason either. I will get the change up soon.

**Review by SJuliez — APPROVED** [review]

**Pull request merged**
