### PR TITLE
Dropship and Large Craft features1

### PR DESCRIPTION
**Pull request by mkerensky**
Figured I'd go ahead and start the PR process on the work I've done here to date. I saw that IOTech might get merged into master over Labor Day weekend and I'm hoping to get any errors in this PR resolved before that happens. 
The very first commits from 8/4-8/7 are framework for my SO Point Defense work, which I intend to pick back up after IOTech is merged into master. 
I also included some custom units, additions to MechSet for a handful of those custom warships, turrets and infantry, and some fixes to the FM: Updates RATs just because I was tired of copying them between new versions and different computers. I'm happy to have them included with the project if you want them. I don't know how to get them out of the PR if you don't.

### CODE REVIEW

**Comment by pheonixstorm** [comment]
Another issue. You don't need to use PRs to update your branch or master. This is where learning the command line or use of a git client comes in handy. You should be able to merge via the console like 
merge -ff from to or soemthing like that.

From a client it would be a lot easier but it would keep out a lot of doubled items such as the maps and unit icons from the first PR.

**Comment by mkerensky** [comment]
Is fetch from upstream the command I'm looking for?

**Comment by pheonixstorm** [comment]
Taking this is slack, be easier I think.

**Comment by arlith** [comment]
I see that there are 916 files that are changed with this PR.  There appears to be a lot of board information added (boards and settings for the map generator), also lots of new BLKs added.  What's with all of these additions?  It's hard to see the code changes, having to sort through all of these new files.

**Comment by mkerensky** [comment]
I did add a lot of custom units and maps. This being my first PR, I was under the impression that if you didn't want to include those in the new version you could selectively omit them. Going forward I am making sure that I stick to a specific feature, fix or set of the same within a single PR instead of bouncing all over the place like this.   If you need me to separate this one out and resubmit just the code changes, I can do so.

**Comment by arlith** [comment]
Yes, I'd prefer that.  If you look in the PR and click on the "Files Changed" tab, that lists all of the changes that will go into MM when the PR is merged.  I *can* checkout the branch for the PR and make my own changes, such are removing files, but it's really tedious and creates a lot of extraneous history.

Generally, I prefer commits to be small and concise, so it's easier to review them.  If I have to review 900+ file changes... it's going to take a looong time for the PR to get reviewed.

**Comment by mkerensky** [comment]
Ok. I'll work on getting the units and maps out, one way or another.

**Comment by pheonixstorm** [comment]
It would be best, or maybe easier, to start with a clean branch and just cherry-pick your changes into it. Consider it a learning experience :stuck_out_tongue_winking_eye:

**Comment by mkerensky** [comment]
My thoughts exactly. There's no actual reason the rebuild needs to be off IOTech, and it's giving me the opportunity to clean up a lot of typos and other formatting mistakes I made the first time through.

**Comment by arlith** [comment]
Making it based off of master rather than IOTech also means I can merge it sooner.  If you base it off of IOTech, I'm not sure if I can merge it.  I guess it doesn't include the IOTech commits, but it could cause merge conflicts.

**Comment by arlith** [comment]
This is going to be resubmitted with the extraneous commits removed.  Closing this version.

**Pull request closed without merging**
