### PR TITLE
Gradle and Github changes for JRE 17 Min

### PR DESCRIPTION
**Pull request by rjhancock**
These are the minimal changes needed for Java 17 as the minimal version.

### CODE REVIEW

**Review by Sleet01 — APPROVED** [review]
Looks good.  I assume this will wait until 0.49.20 is released?

**Review by SJuliez — APPROVED** [review]
I'd like to note that by the time we merge this, the dependencies updates may become downgrades.

**Comment by rjhancock** [comment]
By the time we merge this, I'll do a cursory check to ensure they're updated. :)

Here's hoping it is sooner rather than later.

**Comment by rjhancock** [comment]
Actions are passing. Ready for merge.

**Comment by HammerGS** [comment]
Given the approvals and moving up the 0.50.0 release merging these.

**Pull request merged**
