### PR TITLE
4098: Adding Sprite Camouflage and Damage Export Options

### LINKED ISSUE #4098: RFE - Export Sprite with Camo
I’ve seen this request a few times in the last few years.  

Have the ability to export the image of a sprite with camo or colouring.

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes #4098. Review with whitespace differences off.

### CODE REVIEW

**Review by SJuliez — APPROVED** [review]
line 469 in EntityImage looks like it could be removed. Other than that, looks good and works great!

**Review by Windchild292 — COMMENTED** [review]
I forgot to remove testing code, was having some odd issues with damage export that were because of how I was testing.

**Comment by HammerGS** [comment]
This is really cool! Do you think there would be a way to have it multi-select in the lobby and then save/export a batch at once?

**Comment by Windchild292** [comment]
I considered it while coding, but every way I've thought of has terrible UX. This is because there's no good way to have the same functionality while naming individual files and catching duplicated file names.

**Comment by HammerGS** [comment]
> I considered it while coding, but every way I've thought of has terrible UX. This is because there's no good way to have the same functionality while naming individual files and catching duplicated file names.

Wouldn't something like limit that option to the lobby then leave the naming the same as the unit. Then players could use tools outside of the MegaMek to fix?

**Pull request merged**
