### PR TITLE
Issue 1486 Add option to skip firing turn for mechs/vees that sprint

### PR DESCRIPTION
**Pull request by DM0000**
added check for sprint and TSM in isEligibleForFiring

Only meks with TSM won't be skipped if option is checked

Closes https://github.com/MegaMek/megamek/issues/1486

### CODE REVIEW

**Comment by NickAragua** [comment]
What's special about TSM?

Also, what about industrial TSM?

**Comment by DM0000** [comment]
So TSM users can fire weapons to keep heat up.  They should have 0% accuracy with "You have sprinted" msg.  I can add in the industrial check.

**Comment by NickAragua** [comment]
Per "Sprinting" on page 16 of TO: AR, I'm pretty sure sprinting completely disallows weapons firing, so I don't think allowing weapons fire is the right approach here.

**Comment by gsparks3** [comment]
> Per "Sprinting" on page 16 of TO: AR, I'm pretty sure sprinting completely disallows weapons firing, so I don't think allowing weapons fire is the right approach here.

In the exact same passage:
>[...] may still fire weapons to generate heat, though such firing has no chance of doing damage.

**Comment by NickAragua** [comment]
Wow, never realized that. All right, good to go then.

**Review by NickAragua — APPROVED** [review]

**Pull request merged**
