### PR TITLE
I.S. Turret RATs & Intro Dates Update To I.O.

### PR DESCRIPTION
**Pull request by BLOODWOLF333**
* Added missing " on Savage Wolf mechset entry
* Changed Dropship entry to the correct (3113) model in Republic RAT
* Created 2750 - 3145 Inner Sphere turret RATs rated A - F
* Updated all turret intro dates to the IO production date for the weapons

### CODE REVIEW

**Comment by NickAragua** [comment]
Man, this is going to break my hacky MekHQ turret generation fix.

**Comment by BLOODWOLF333** [comment]
Turret generation fix?

**Comment by NickAragua** [comment]
Yeah, MekHQ PR #417. Tht's fine, I'll update it after your data changes get merged.

**Comment by HammerGS** [comment]
Merged in.

**Pull request merged**
