### PR TITLE
MekHQ 1529: Reimplementing negative armour check

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes MegaMek/MekHQ#1529

### CODE REVIEW

**Comment by sixlettervariables** [comment]
Did the commit which commented it out explain why?

**Comment by Windchild292** [comment]
It did not

**Comment by sixlettervariables** [comment]
How did this affect runs of the unit verifier? I haven't quite gotten to adding that to the CI system.

**Comment by Windchild292** [comment]
It will cause failures on illegal units that have been released would be my bet... although we probably want to fail on those?

**Pull request merged**
