### PR TITLE
WIP: Always show the map during the game

### PR DESCRIPTION
**Pull request by mjog**
This patch set removes the interstitial round/phase report, so that the board view is always shown. Instead of the interstitial reports, phase reports are displayed via the same interface as server/player chat, and phases that do not require player action (e.g. heat) have their results displayed, but are automatically advanced through. The existing round report can still be accessed via View > Round Report for people who prefer the traditional interface, and so as to be able to easily view previous round's reports.

perma-map

The main benefits of this are:

* Removing the visual and operational interruptions caused by the map and the interstitial reports appearing and disappearing, and removing the need to manually advance through no-action-required phases, greatly improves the flow of a game
* Being able to consult the map when reading the round report, to examine mentioned units and hexes, see exploded meks, etc

But there's also other good reasons to do it:

* In the future, details in the round reports could be made into active links, so that e.g. clicking on a hex reference would scroll the hex into view (I am keen to implement that if this lands)
* A much more simple implementation: Lot of custom widget-like code and special-casing was removed, less client state to reason about, etc. There's more low hanging fruit there as well - the report phases may be able to be removed from the protocol in the future, for example.

Automatically advancing though no-action-required phases is perhaps controversial, but in the end it's no actual change, just less busy-work when playing a game - the phases still happen, the results are still displayed.

Most of this work involves replacing the existing ChatterBox and ChatterBox2 classes with a new, Swing based implementation of the same, so that JTextPanes could be used to display the HTML needed for the round reports. This cut down on a lot of custom code, since ChatterBox2 (as an IDisplayable) basically had to re-implement its own widget toolkit themselves. As such, the replacement is an order of magnitude less code to maintain.

This is still very much a WIP, some things on the TODO include:

 * Handle Tactical Genius initiative re-rolls
 * Check string l18n
 * For the chat interface:
   * Implement theming
   * Move the scrollbar to the left / remove it
   * Fix some transparency artifacts
   * General polish
 * Your concern here

I'm mostly after feedback at the moment about whether or not there is any interest in this actually being merged. Should I keep working on this or not?

I highly recommend anyone who is doubtful or doesn't like the idea take it for a test drive at least - even at the moment it feels *really* good when playing a game.

### Summary of feedback

This is a summary of common feedback I'm hearing that should be taken into account. Will update the list as more rolls in.

 * Transparency may well be an issue
 * Should be no loss of accessibility & functionality
 * Mixing chat and round reports could mean they get lost

### CODE REVIEW

**Comment by sixlettervariables** [comment]
My only concern is w.r.t. accessibility of the new chat box and workflow. As long as we do not regress there, I'm generally not opposed.

**Comment by mjog** [comment]
NB this is related to some other changes I'd like to look into, see #3071 for details about that larger picture. Irrespective of what happens there, I'd still be super keen to get this merged.

**Comment by mjog** [comment]
> My only concern is w.r.t. accessibility of the new chat box and workflow. As long as we do not regress there, I'm generally not opposed.

Yep, I definitely don't want any regressions there.

I feel that moving to a Swing widget based chatbox is actually a vast improvement, since it gets standard things like tab navigation, copy and paste, and text editing keyboard shortcuts working for free.

But that aside, is there anything specific accessibility wise that's important though - is it the keyboard shortcuts? Tab navigation? Something else?

**Comment by HammerGS** [comment]
Forum thread set up for feedback - https://bg.battletech.com/forums/megamek-games/feedback-wanted-proposed-changes-to-megameks-uiux/

But I suspect we'll get feedback all over the place.

**Comment by mjog** [comment]
> * This could lead to some serious user discontent if the game is configured to "skip ineligible during physical phase". Right now, you have an opportunity to type /victory and do other "before end of turn" stuff  (e.g. turn heat sinks on/off, declare hidden unit reveals, switch ECM modes, etc) during one of the round report phases. With this change, that's no longer the case. So I think we need to look into retaining some kind of "before the end of the turn" interaction mode.

Hmm, interesting point. My motivation for working on this is the ~100 unit (per-side) battles I tend to play. In those cases, I already have to cycle through that many units at least twice (movement & ranged phases), so I tend to do those sorts of actions during one of those two phases, rather than right at the end.

I can see that for people playing smaller games however and who really want to fine tune every unit would find skipping the end phase annoying. One obvious option would be to not skip the end phase - make some action required to finish each round, but that would interrupt the flow of asynchronous double blind games. Another option might be to cycle through units during the end phase that have available actions, and perhaps make a pref to enable that to be skipped or something - make the end phase work a lot like movement & combat phases currently do.

> * Since the "chat" UI will now be a lot more heavily used, do we want to look into using a more conventional default keybind to activate it? Like, one that's used by a lot of other games. I remember it was recently changed from 'Enter' to something pretty obscure, which was fine at the time because nobody used the chat window anyway.

Yah good suggestion, but... do you know what other games use? I don't. :)

> * Can we make the transparency adjustable? It's going to be hell trying to read that if the map is snow tiles.

Yeah, I made it transparent for parity with the existing chat, but I agree it doesn't work superbly well. Happy to improve it.

**Comment by HammerGS** [comment]
I've given this a try and I have some mixed feelings for it.  

image

While I like the ability to quickly reference the round report I can't seem to make it go away. As the screen shot shows I feel like I'm missing half my game board. The transparency kinda works but all the text over it is very distracting. 

Could you do something like a arrow that causes it to slide into the side out of view. Then click the arrow and have it pop back out. In other games I found it very useful to scroll back and see things while the map is available. 

My initial thoughts...

**Comment by mjog** [comment]
Thinking about feedback here and in the forums, and looking into the design and implementation some more, I think this needs to be dialled back a bit.

The approach I'm now looking into is converting the round reports (both in-window and the "mini" round report) into a dockable, collapsible sidebar, keeping the perma map, but keeping round reports and chat separate:

MM Dockable Round Report

The changes to the chat here (conversion to Swing components) is still worthwhile, so I'll spin them out into a different PR.

**Comment by HammerGS** [comment]
I think that plan makes more sense to me. When you have some code of it I'll be sure to pull the branch and try it again.

**Comment by mjog** [comment]
I have updated this per the mock-up above.

It's currently based off of the branch #3125 since it re-uses the detachable pane introduced there. Still need to do something about tactical genius, but it otherwise is looking pretty good. It currently pauses at the end of each round to let people adjust unit settings etc, but plan on making that configurable so people who prefer play to flow can get that going.

I also have a bunch of additional updates to round reports to make pretty much every player, entity, and hex reference in the round reports hyperlinked (most of them are just plain text at the moment), but I'll push that as a separate PR since it's a *lot* of near-identical changes that will otherwise make this hard to review.

Currently looks something like this:

Screenshot from 2021-09-07 23-35-14

**Comment by HammerGS** [comment]
Gave this a try, and first impression I like it. That was with one quick 2 v 2 battle. Only thing I found jarring was the after firing phases it went straight to next round. I'm used to seeing each phase so that thru me a bit. 

But I like where this is going.

**Comment by HoneySkull** [comment]
I wonder if a popup dialog appeared in the middle of map - or some other type of fading graphic that announced the beginning of  a new round would help with the jarring effect of moving to a new round.  Street Fighter style :) "Round 3 - Fight!"

I would love to try this out.  In my opinion, this is where the UI is begging to go in my sub-conscience.

Note:  The unit information window takes up a lot of real-estate - I'm wondering if that should be half height, and then use the bottom area under it for unit selection, or message chat window to get that off the map area.  Or mini-map?

**Comment by mjog** [comment]
> I wonder if a popup dialog appeared in the middle of map - or some other type of fading graphic that announced the beginning of a new round would help with the jarring effect of moving to a new round. Street Fighter style :) "Round 3 - Fight!"

That'd be cool. Maybe a good idea for a Solaris 7 plugin? :)

> I would love to try this out. In my opinion, this is where the UI is begging to go in my sub-conscience.

You can check this branch out and build it without too much hassle if you're familiar with Java dev. Would be happy to get your feedback if you do.

> Note: The unit information window takes up a lot of real-estate - I'm wondering if that should be half height, and then use the bottom rea under it for unit selection, or message chat window to get that off the map area. Or mini-map?

I don't disagree, but that's maybe something for a different PR. ;) You can at least hide it pretty easily using the keyboard shortcuts.

**Comment by HammerGS** [comment]
Can't wait to give these fixes a try. We had some feedback on the dockable display on our Discord and will leave it here. 

From Lisbon
So, a couple of thoughts about the dockable unit display (these are the very first impressions after the battle started):
- It's a bit big, as in, bigger than it needs to. All the info is the same, but the space is almost double on my monitor compared to the little window I usually have on the corner just outside the main battle window
- When using the display as that mentioned little window, the elements in the various tabs don't update very well, specially the armor and the "extras" tab, because in the undocked version they keep the format of the original docked one, so unless we use a large height for the window, a couple of elements get hidden
Minor stuff, but I figured I would share"

and

A bit of extra feedback: the game no longer saves unit display window position, so every time you load a game, the unit display is docked. It also doesn't save size (but it does save position) within the same game session

**Comment by JonhyBurner** [comment]
I would also like to point out that if the armor mock-up were to be pulled up a bit, the map would fit neatly on the lower part of the docked display, with only minor (less used) elements hidden. Or the extra space could be used for something else.

**Comment by HammerGS** [comment]
Went to test this and getting the following error. Likely PEBKAC with the user but posting to make sure.

image

**Comment by mjog** [comment]
> Went to test this and getting the following error. Likely PEBKAC with the user but posting to make sure. 

@HammerGS which version of the JDK are you using? Builds find for me under Linux using OpenJDK 11.

**Comment by mjog** [comment]
Also, thanks for the feedback about the unit display, but that's best taken care of in another ticket, since this is about the perma-map.

If you can open a new issue about anything else you find with the dockable unit display and @ me there, I'll take a look.

**Comment by HammerGS** [comment]
> > Went to test this and getting the following error. Likely PEBKAC with the user but posting to make sure.
> 
> @HammerGS which version of the JDK are you using? Builds fine for me under Linux using OpenJDK 11 - CI builds it fine as well.

image

**Comment by mjog** [comment]
@HammerGS think I just fixed the problem - want to try again?

**Comment by HammerGS** [comment]
Being the data guy have some limited command line skillz.  When I try to update I get this:

```
X:\MegaMek_Workspace\megamek\megamek>git pull https://github.com/mjog/megamek.git perma-map
remote: Enumerating objects: 162, done.
remote: Counting objects: 100% (162/162), done.
remote: Compressing objects: 100% (27/27), done.
Receiving objects:  88% (143/162)used 162 (delta 111), pack-reused 0R
Receiving objects: 100% (162/162), 18.69 KiB | 797.00 KiB/s, done.
Resolving deltas: 100% (111/111), completed with 8 local objects.
From https://github.com/mjog/megamek
 * branch                  perma-map  -> FETCH_HEAD
Auto-merging megamek/src/megamek/common/Game.java
CONFLICT (content): Merge conflict in megamek/src/megamek/common/Game.java
CONFLICT (add/add): Merge conflict in megamek/src/megamek/client/ui/swing/RoundReportPane.java
Auto-merging megamek/src/megamek/client/ui/swing/RoundReportPane.java
Auto-merging megamek/src/megamek/client/ui/swing/ClientGUI.java
CONFLICT (content): Merge conflict in megamek/src/megamek/client/ui/swing/ClientGUI.java
Removing megamek/data/images/units/mechs/Shadow Hawk IIC.png
Removing megamek/data/images/units/mechs/Shadow Hawk IIC 9.png
Removing megamek/data/images/units/mechs/Shadow Hawk IIC 8.png
Removing megamek/data/images/units/mechs/Shadow Hawk IIC 7.png
Removing megamek/data/images/units/mechs/Shadow Hawk IIC 6.png
Removing megamek/data/images/units/mechs/Shadow Hawk IIC 5.png
Removing megamek/data/images/units/mechs/Shadow Hawk IIC 4.png
Removing megamek/data/images/units/mechs/Shadow Hawk IIC 3.png
Removing megamek/data/images/units/mechs/Shadow Hawk IIC 2.png
Removing megamek/data/images/units/mechs/Masakari (Warhawk).png
Removing megamek/data/images/units/mechs/Masakari (Warhawk) H.png
Removing megamek/data/images/units/mechs/Masakari (Warhawk) F.png
Removing megamek/data/images/units/mechs/Masakari (Warhawk) E.png
Removing megamek/data/images/units/mechs/Masakari (Warhawk) D.png
Removing megamek/data/images/units/mechs/Masakari (Warhawk) C.png
Removing megamek/data/images/units/mechs/Masakari (Warhawk) B.png
Removing megamek/data/images/units/mechs/Masakari (Warhawk) A.png
Removing megamek/data/images/units/mechs/Longbow LGB-8V.png
Removing megamek/data/images/units/mechs/Longbow LGB-7V.png
Removing megamek/data/images/units/mechs/Longbow LGB-14C.png
Removing megamek/data/images/units/mechs/Longbow LGB-13NAIS.png
Removing megamek/data/images/units/mechs/Longbow LGB-13C.png
Removing megamek/data/images/units/mechs/Longbow LGB-12R.png
Removing megamek/data/images/units/mechs/Longbow LGB-12C.png
Removing megamek/data/images/units/mechs/Longbow LGB-0W.png
Removing megamek/data/images/units/mechs/Longbow LGB-0C.png
Removing megamek/data/images/units/mechs/Hellion G.png
Removing megamek/data/images/units/mechs/Hellion F.png
Removing megamek/data/images/units/mechs/Hellion E.png
Removing megamek/data/images/units/mechs/Hellion D.png
Removing megamek/data/images/units/mechs/Hellion C.png
Removing megamek/data/images/units/mechs/Hellion B.png
Removing megamek/data/images/units/mechs/Hellion A.png
Automatic merge failed; fix conflicts and then commit the result.
```
But I have been able to use it and think its working well. I wondering if the branch got updated to our current Master if we did a MegaMek only test release of this. We can let players test it, then make a plan to get it committed.  Thoughts?

**Comment by mjog** [comment]
@HammerGS maybe try doing a `git pull -f`? Or delete the branch (`git branch -D perma-map`) and pull it down again?

Happy to get some more wider testing, but there's a few small things I'm chasing up still with it. Give me a week or two before going wide with it?

**Comment by HammerGS** [comment]
@mjog Hi and Happy New Year. Wanted to check in and see how things are going on this one. It's still got some buzz in the community from where we teased it.

**Comment by SJuliez** [comment]
I believe this is now superseded by @kuronekochomusuke 's UI changes.

**Pull request closed without merging**
