### PR TITLE
Entity Sprites

### PR DESCRIPTION
**Pull request by SJuliez**
Not much in the way of new gameplay features ;)

What's changed:

- activated antialiasing and proper scaling; (for the unit icon itself it doesn't make a difference)
- the unit labels scale only slightly with zoom level and remain readable at all scales
- the labels will fan out when multiple units are stacked in a hex
- the labels will dodge occupied neighboring hexes so they don't overlap as much
- additional info is displayed as little blobs beside the label
- the additional info is: altitude/flight level/depth (cyan, sky color :)), hidden/unseen (also when translucent), digging in, transporting, and unit health (colored blob), and probably something else I forgot
- if the unit is made translucent because it's hidden only the unit icon is affected, not the label and other info
- critical status is displayed as it used to be as text over the icon, probably even more visible now
- when zoomed far out, critical status is replaced by a big "!" over the icon (when it would be unreadable anyway)
- when there's some really critical status (red-colored), the unit label is tinted red.
- all the dodging and stacking has limits of course because the labels are often very long and the hexes are so small, but the limits are reached later they used to
- Note: I changed boardview1 to always redraw all entity sprites when it would normally only redraw the current one. This is so that sprites are painted correctly (label stacking/dodging). It would be possible to only redraw a few, but I cant really see the point. Redrawing all sprites won't take more than a millisecond. I have found no bad behavior in the game, but maybe something turns up.

Check it out!

** Edit: I wanted to mark the strings ($NLS...) but forgot. I can add that later.

Stuff to do:
- Unit shadow
- stacking units hiding information of all but the topmost unit
- health bars (anyone got a good idea where to put them?)
- I didnt test secondary position stuff (dropships? dont know)
- character encoding for special characters in pilot names (tooltips)
- add tooltip info for all status
- units on the left coloumn of the board shouldnt have their labels extend towards the left. same with right

### CODE REVIEW

**Comment by arlith** [comment]
> health bars (anyone got a good idea where to put them?)

How were you planning on doing health bars?  I think that there are already two forms of health bar in the game, aren't there?  By default, the unit will display two green bars, which are basically just a representation of current armor over total armor and current internals over total internals.  There's also the damage indicator which shows green/orange/yellow/red/black depending on the current "damage" state of the unit (undamaged, lightly damage, moderately damaged, heavily damaged, crippled.

Did you have something different from this in mind?

**Comment by SJuliez** [comment]
Hello,


Nothing different. The current healthbars are just in a place that may sometimes be occupied by a label. The labels are too long as they are so they're no good place to stick health info into.  Question to me is, are the health bars important? Its not like a mech has hit points in TW as opposed to AS. It can be killed when the health bar is at 90% and it can stand when the health bar is at 0%. I'd rather implement a useful armor info like the unit window armor tab that gets shown on keypress for all units on the board.


________________________________
Von: Nicholas Walczak <notifications@github.com>
Gesendet: Montag, 29. Februar 2016 20:34
An: MegaMek/megamek
Cc: SJuliez
Betreff: Re: [megamek] Entity Sprites (#47)


health bars (anyone got a good idea where to put them?)

How were you planning on doing health bars? I think that there are already two forms of health bar in the game, aren't there? By default, the unit will display two green bars, which are basically just a representation of current armor over total armor and current internals over total internals. There's also the damage indicator which shows green/orange/yellow/red/black depending on the current "damage" state of the unit (undamaged, lightly damage, moderately damaged, heavily damaged, crippled.

Did you have something different from this in mind?

-

**Comment by arlith** [comment]
Overall, I think this looks good.

I found that the label position didn't update during deploy; I fixed that before merging.

I did test with landed dropships and it seemed to work fine.

I found the labels more readable by default, however when the unit is hidden, the translucent gray wasn't as easy to read (which I think is probably a legacy problem as well.  Maybe adding a white outline to the gray text would help?

Also, it occurred to me that it might be nice to make some of the colors adjustable as advanced options (this is pretty easy to do, so we should probably consider doing it).

**Comment by SJuliez** [comment]
Hi again,


thanks. Also for testing, I wanted to test anything with a secondary position, but forgot.


Which "hidden" do you mean? I think I made the labels stay opaque when a unit is double-blind-hidden from the enemy - only the unit icon should be translucent. Do you mean deployed-as-hidden? I have not looked at this at all, but can do.


Colors: yes, why not, I'll put it on todo.


________________________________
Von: Nicholas Walczak <notifications@github.com>
Gesendet: Dienstag, 1. März 2016 13:49
An: MegaMek/megamek
Cc: SJuliez
Betreff: Re: [megamek] Entity Sprites (#47)


Overall, I think this looks good.

I found that the label position didn't update during deploy; I fixed that before merging.

I did test with landed dropships and it seemed to work fine.

I found the labels more readable by default, however when the unit is hidden, the translucent gray wasn't as easy to read (which I think is probably a legacy problem as well. Maybe adding a white outline to the gray text would help?

Also, it occurred to me that it might be nice to make some of the colors adjustable as advanced options (this is pretty easy to do, so we should probably consider doing it).

-

**Comment by arlith** [comment]
I mean a colloquial "hidden" and not hidden units "hidden."  By that, I mean that units that are not visually spotted by enemies when doubleblind rules are in.  I'll attach a screenshot.

screenshot-5

Here's the saved game I was testing with: [test.sav.gz](https://github.com/MegaMek/megamek/files/153699/test.sav.gz)

**Comment by SJuliez** [comment]
Ah ok, this is the isDone() style. Maybe a bit too subdued. Any lighter and it will be practically indistinguishable from an active unit. I wanted to avoid too much color but maybe active units should have greenish text.


________________________________
Von: Nicholas Walczak <notifications@github.com>
Gesendet: Dienstag, 1. März 2016 14:04
An: MegaMek/megamek
Cc: SJuliez
Betreff: Re: [megamek] Entity Sprites (#47)


I mean a colloquial "hidden" and not hidden units "hidden." By that, I mean that units that are not visually spotted by enemies when doubleblind rules are in. I'll attach a screenshot.

[screenshot-5]<https://cloud.githubusercontent.com/assets/13815237/13443544/0e787f52-dfc7-11e5-9417-5e36a323b01d.png>

[https://cloud.githubusercontent.com/assets/13815237/13443544/0e787f52-dfc7-11e5-9417-5e36a323b01d.png]

Here's the saved game I was testing with: test.sav.gz<https://github.com/MegaMek/megamek/files/153699/test.sav.gz>

-

**Comment by Akjosch** [comment]
I'd like to add that I very much like and use the health bars. Because fuck me if I remembered if it was Bulldog \#17 or Bulldog \#19 that was heavily damaged and needed to pull out of the fight from one turn to the next, much less for multiple turns and every of the 30+ units on my side.

**Comment by arlith** [comment]
@SJuliez Huh, I thought it was because the unit wasn't spotted.  I thought the different between done or not was white text with a light gray background vs a dark gray background for when the unit has moved.  I might've just gotten them mixed up.

@Akjosh  I kind of had a situation like that in mind when I made my previous comment.  I don't think health bars should go away.  It would be nice though to get information about armor distribution without having to "view" a unit in the UnitDisplay.  I find using the unit display ends up taking more time, which is why weapon lists in the tool tips has been great.  That has really cut down on the number of times I've had to "view" enemy units.

**Comment by SJuliez** [comment]
I'm not touching them ;)


There is also the damage bubble that can be activated in the menu. It doesnt have the same "damage resolution" but it does show green/yellow/red.


________________________________
Von: Nicholas Walczak <notifications@github.com>
Gesendet: Mittwoch, 2. März 2016 11:01
An: MegaMek/megamek
Cc: SJuliez
Betreff: Re: [megamek] Entity Sprites (#47)


@SJuliez<https://github.com/SJuliez> Huh, I thought it was because the unit wasn't spotted. I thought the different between done or not was white text with a light gray background vs a dark gray background for when the unit has moved. I might've just gotten them mixed up.

@Akjosh<https://github.com/Akjosh> I kind of had a situation like that in mind when I made my previous comment. I don't think health bars should go away. It would be nice though to get information about armor distribution without having to "view" a unit in the UnitDisplay. I find using the unit display ends up taking more time, which is why weapon lists in the tool tips has been great. That has really cut down on the number of times I've had to "view" enemy units.

-

**Comment by SJuliez** [comment]
On the labels: I found the light background/dark background thing 100% unintuitive. If I see a bunch of units, 50% with light labels, the other 50% with dark, I wouldn't know which ones were still available. And I have used MM a bit. Graying out is the way to signal unavailability imo. But there is always room for improvement. I'll keep it in mind.


________________________________
Von: Nicholas Walczak <notifications@github.com>
Gesendet: Mittwoch, 2. März 2016 11:01
An: MegaMek/megamek
Cc: SJuliez
Betreff: Re: [megamek] Entity Sprites (#47)


@SJuliez<https://github.com/SJuliez> Huh, I thought it was because the unit wasn't spotted. I thought the different between done or not was white text with a light gray background vs a dark gray background for when the unit has moved. I might've just gotten them mixed up.

@Akjosh<https://github.com/Akjosh> I kind of had a situation like that in mind when I made my previous comment. I don't think health bars should go away. It would be nice though to get information about armor distribution without having to "view" a unit in the UnitDisplay. I find using the unit display ends up taking more time, which is why weapon lists in the tool tips has been great. That has really cut down on the number of times I've had to "view" enemy units.

-

**Comment by arlith** [comment]
yea, I'd agree with you.  It wasn't a feature I added, but was present when I joined.  I actually didn't realize it worked that way for a long time, and then I found that it was a "feature" that many players didn't seem to know about.  It used to be that you couldn't tell from the tooltip either, but that was rectified when you updated the tooltips a while back.

However, I think we may have lost an indicator for when a unit isn't spotted by an enemy.  I think that previously, this was handled by making the unit icon translucent, but only in isometric mode.  In non-iso mode, the only thing made translucent was the unit label.

**Comment by SJuliez** [comment]
hidden

Is this screenshot visible? I dropped it into github directly.
Well if it is, this is how a hidden and an unseen unit look like in a double blind savegame I use.

**Comment by SJuliez** [comment]
Ach.... I just noticed that translucency does not work when using Iso mode... not game breaking but another TODO :D

**Comment by SJuliez** [comment]
@Akjosch this is what I was thinking about (it's not yet refined at all):
 It should only be on screen when we hold e.g. the ALT key. 

unithlt

**Comment by Akjosch** [comment]
@SJuliez Looks cool, but I'm mostly fine with just the bars, with *maybe* a few extra indicators on them denoting how many hit locations are stripped of armour. When you have 100 or more units on the map, as I often end up doing, this kind of display would simply not work.

Now, pack a small version of the silhouettes on the side in a tabular view along with unit name, type, damage bars, MP, crew hits and so on and I can see it being *very* useful.

**Comment by pheonixstorm** [comment]
If it only shows when you hit alt on mouseover I think it would work very well even with a large amount of unit. If, however, it shows up for ALL units when you hit alt then that could get a tad annoying. Even having it popup when you target the unit would be fine. 

So click target, damage box pops up, click another target and first damage box goes away and new damage box pops up next to the new target.

Far more useful than right click, view target, click armor tab, then right click select active unit.

**Comment by arlith** [comment]
@SJuliez  RE: transparency/unspotted unit screenshot:  yes, I can see the screenshot, and yes I think that is far more readable.

RE: armor display.  Akjosch does give me an idea; there could be a toggle for the unit display that switches between unit icon and armor display.  This could be nice for your own force (although I could also see it being nice for the enemy units as well, and this wouldn't help with that).

**Comment by SJuliez** [comment]
Thanks, guys! 4 people 5 opinions...

@all:

Just to be absolutely clear, I want to rephrase this: My plan was to make those blocks of armor info be onscreen when and only when ALT (or whatever is bound) is down. They'll vanish on key-up. They'll never appear when the key isn't pressed. For me this is what I miss in MM - at a glance information about all units on board. Having to single-click them (even when targeting e.g.) defeats the purpose. I find keybinds very useful (10 years of WoW...) but I understand that some people might like a more static display.

Also, I already made the blocks avoid overlap. So the display should still make sense even with a lot of units on board.

@Akjosch I can see that with 100 units on the board if you want to finish a game before 2100 AD you just cannot care about a Mech's right toe. However if you place 100 units in tabular view finding that particular Atlas might be annoying.

Nicholas' idea is a good one, too, I think.

**Comment by SJuliez** [comment]
@Akjosch Would you share a savegame of so many units with me? I'd like testing with it. Thanks.


________________________________
Von: Akjosch <notifications@github.com>
Gesendet: Mittwoch, 2. März 2016 13:51
An: MegaMek/megamek
Cc: SJuliez
Betreff: Re: [megamek] Entity Sprites (#47)


@SJuliez<https://github.com/SJuliez> Looks cool, but I'm mostly fine with just the bars, with maybe a few extra indicators on them denoting how many hit locations are stripped of armour. When you have 100 or more units on the map, as I often end up doing, this kind of display would simply not work.

Now, pack a small version of the silhouettes on the side in a tabular view along with unit name, type, damage bars, MP, crew hits and so on and I can see it being very useful.

-

**Comment by Akjosch** [comment]
@SJuliez I only have one with about 35 or so. I don't tend to keep them for long, sorry.
[savegame_aquagea_2.sav.gz.zip](https://github.com/MegaMek/megamek/files/157744/savegame_aquagea_2.sav.gz.zip)

**Comment by Akjosch** [comment]
@SJuliez Just remembered that you might need the customs used. 
[custom.zip](https://github.com/MegaMek/megamek/files/158179/custom.zip)

**Comment by arlith** [comment]
Custom units are only need for MHQ cpnx files.  If you've got a MM saved file, the unit data is already serialized in the saved game.

**Comment by SJuliez** [comment]
@Akjosch Thanks, great savegame! Serious woods. Now with all the clutter on that map I can see that the labels are a bit too translucent. I'll work on that.

**Comment by SJuliez** [comment]
@Akjosch 
@arlith 
What do you guys think? 
- labels much less translucent
- units not done for the phase (may still move etc.) with green text, white text when done
- could add a client setting to change the green to something else but I think green is an intuitive color for this (sadly it doesnt stick out much from woods)


unitdone1
unitdone3

**Comment by arlith** [comment]
The labels definitely stand out more.  I was wondering, what about using the same teal/light blue color that we use in the UnitOverview?  The UnitOverview creates a border around units that is either purple (selected), teal (not selected by able to be selected) and  black (not selectable).  Sharing the same colors would create some consistency.  I'm not sure if those colors are tied into an advanced option or not, you could look in the UnitOverview code.

**Pull request merged**
