### PR TITLE
Dropship damage

### LINKED ISSUE #840: DropShip to DropShip fire conversion error 0.43.6
I ran a short space battle through MekHQ's instance of MegaMek (not launched from HQ, but the instance that is included in the HQ release).  The reason is was so short was that apparently my Union Class DropShips were equipped with Micro Nuclear Weapons.

When I fired on a Fighter, the LRM bays acted normally.  When I fired on an Avenger Class DropShip, the damage went from 5 damage per cluster against the Lucifer II, to 65 damage per cluster against the Avenger.  Needless to say the DropShip was wrecked instantly.

Weapons fire for Union (2708) (Femme Fatale)
    LRM Bay at Lucifer II LCF-R16K #4 (Princess); needs 7, rolls 7 :  - Glancing Blow - 
        LRM 20 at Lucifer II LCF-R16K #4 (Princess); 
hits.

        Lucifer II LCF-R16K #4 (Princess) takes 5 damage to LWG.
            19 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (5+2) = 7 : no effect.

        Lucifer II LCF-R16K #4 (Princess) takes 5 damage to LWG.
            14 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (8+2) = 10 : no bombs to destroy.

        Lucifer II LCF-R16K #4 (Princess) takes 2 damage to LWG.
            12 Armor remaining.

        LRM 20 at Lucifer II LCF-R16K #4 (Princess); 
hits.

        Lucifer II LCF-R16K #4 (Princess) takes 5 damage to AFT.
            21 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (4+1) = 5 : no effect.

        Lucifer II LCF-R16K #4 (Princess) takes 4 damage to LWG.
            8 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (8+1) = 9 : no bombs to destroy.

    LRM Bay at Lucifer II LCF-R16K #4 (Princess); needs 7, rolls 6 : misses

    LRM Bay at Avenger (2816) (Princess); needs 8, rolls 9 : 
        LRM 20 at Avenger (2816) (Princess); 
hits.

        Avenger (2816) (Princess) takes 65 damage to RS.
            138 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (9+1) = 10 : An Cargo bay door is destroyed!

        Avenger (2816) (Princess) takes 65 damage to AFT.
            115 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (6+1) = 7 : no effect.

        Avenger (2816) (Princess) takes 65 damage to NOS.
            165 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (7+1) = 8 : Sensors Hit!

        Avenger (2816) (Princess) takes 13 damage to RS.
            125 Armor remaining.

        LRM 20 at Avenger (2816) (Princess); 
hits.

        Avenger (2816) (Princess) takes 65 damage to RS.
            60 Armor remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (5+1) = 6 : no effect.

        Avenger (2816) (Princess) takes 65 damage to RS.
            Armor destroyed.
 5 damage transfers to the SI. 19 SI remaining.
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (5+1) = 6 : no effect.
            Possible critical hit (SI damaged); needs 8, rolls (6+1) = 7 : no effect.

        Avenger (2816) (Princess) takes 26 damage to RS.
 26 damage transfers to the SI. 0 SI remaining.
*** Avenger (2816) (Princess) DESTROYED by Structural Integrity Collapse! ***
            Possible critical hit (Damage threshold exceeded); needs 8, rolls (5+1) = 6 : no effect.
            Possible critical hit (SI damaged); needs 8, rolls (8+1) = 9 : No undestroyed transport bay found.
[gamelog.zip](https://github.com/MegaMek/megamek/files/1598248/gamelog.zip)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1598251/megameklog.txt)

### PR DESCRIPTION
**Pull request by AaronGullickson**
This PR fixes #840. The problem was in MissileWeaponHandler.java:

```java
        //This is for firing ATM/LRM/MML/MRM/SRMs at a dropship, but is ignored for ground-to-air fire
        //It's also rare but possible for two hostile grounded dropships to shoot at each other with individual weapons
        //with this handler. They'll use the cluster table too.
        if (entityTarget != null 
                && entityTarget.hasETypeFlag(Entity.ETYPE_DROPSHIP) 
                && waa.isAirToAir(game) || (waa.isAirToGround(game) && !ae.usesWeaponBays())) {
            nDamPerHit = attackValue;
        } else {
            //This is for all other targets in atmosphere
            nDamPerHit = calcDamagePerHit();
        }
```

Its unclear what this code was trying to accomplish. With vanilla settings, this code changed nothing about the way that damage is applied to dropships in air to air situations. Furthermore, the code seems to be relying on some unsafe assumptions upstream about what kinds of attacks are using cluster damage vs single damage. This is what was causing the problem with aero sanity. If this code is serving some purpose then it probably belongs somewhere further upstream when that determination about cluster hitting or singular damage is being made. However, I think without the code, everything with vanilla options is working by the RAW and aero sanity damage is working properly.

### CODE REVIEW

**Comment by NickAragua** [comment]
I'm not an expert on air-to-air damage, so how much damage is an LRM/20 bay (with a single LRM/20 in it) supposed to do?

**Comment by AaronGullickson** [comment]
12. It takes the average from the cluster hit table.

**Comment by AaronGullickson** [comment]
After talking with @mkerensky, it appears that the reason for this code is to make sure that attacks on droppers are affected by point defense when advanced point defense rules are in play. This is because calcAttackValue subtracts the point defense value from damage so if damage doesn’t come from attack value it won’t have the reduction applied. However, this is not the best place for this and it should really be in calcAeroDamage is which is intended to collect all of the aero cases. So I am trying to fix that code now.

**Comment by sixlettervariables** [comment]
Superseded by #1258.

**Pull request closed without merging**
