### PR TITLE
Show % BV remaining in round reports

### PR DESCRIPTION
**Pull request by luiges90**
Mostly for AtB play. Typing `/checkbv` every turn isn't exactly fun. 😉

### CODE REVIEW

**Comment by arlith** [comment]
You submitted a patch on SF a few years ago for specifying weapon data in files (https://sourceforge.net/p/megamek/patches/463/).  Have you kept this code up-to-date?

**Comment by luiges90** [comment]
@arlith No. Actually I lost the patch....... 😞 

I may revisit it later, given I have free time to spare.

**Comment by arlith** [comment]
It may be possible to salvage it from the patch on SF, although I can all but guarantee it won't merge well, but I'm not sure if it's easier to fix the conflicts, or just start over.

**Comment by HammerGS** [comment]
@luiges90 Not sure if it helps but the patch is still on SF - https://sourceforge.net/p/megamek/patches/463/

**Pull request merged**
