### PR TITLE
Fix 5825: ASF Low Altitude LOS, levels, and ground map terrain blocking other terrain

### LINKED ISSUE #5825: LOS Being Drawn At Incorrect Altitudes On Low-Alt Map
### Environment
0.50.0 nightly snapshot 07/28/2024, Windows 10 x64

### Description
#5797 added proper support for aerospace units measuring LOS through low-altitude map terrain. However, there seems to have been an issue. LOS is not being drawn as it should. From testing, it appears to draw LOS to and from units as if those units were one altitude above their real altitude.

### Files
image
image
image
image
image
image
image
image

### PR DESCRIPTION
**Pull request by Sleet01**
Reverted some low-altitude map changes, extracted relevant code to Low Alt-specific functions, and updated some LOS measuring and drawing functions to work with Altitudes.  Marking as Draft for now so more testing can get run.

Current visuals look like:
image
image

With Diagramming LOS:
image

Testing so far:
- Ran human-vs-bot ASF games on Low Altitude maps
- Ran all 3 projects' unit tests

Close #5825

### CODE REVIEW

**Comment by SJuliez** [comment]
Ready for review? You wrote that this was marked as draft but it isnt.

**Comment by Sleet01** [comment]
> Ready for review? You wrote that this was marked as draft but it isnt.

Sorry, that's the 2AM brain talking.  I'll mark it as draft and get some more testing in.

**Comment by pokefan548** [comment]
Did some testing clients-akimbo on a snapshot provided by Sleet. Rigorous testing of vanilla LOS, and some brief testing of Diagramming and Dead Zone LOS rules. All results point to everything working as intended.

**Comment by Sleet01** [comment]
I also got some more testing in, although some just proved that the _previous_ code was busted.  Ready to pull.

**Pull request merged**
