### PR TITLE
MekHQ #251: Force Generator Unit Table Faction Fallback

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes https://github.com/MegaMek/mekhq/issues/251 by adding parent faction fallbacks (going back 10x, to prevent infinite looping while handling nested forces (like MOC.pm). This also fixes the Magistracy of Canopus Planetary Militia's parent faction as a typo.

### CODE REVIEW

**Comment by neoancient** [comment]
What's the issue you're trying to fix? The selected faction should inherit the parent factions' units, so if there aren't any for the selected faction, there shouldn't be any for the parent factions.

**Comment by HammerGS** [comment]
We are consistently getting report of players gettIng Fedcom contracts in AtB and no force being generated. Generally between 3060-3067 during the Civil war era.

**Comment by Windchild292** [comment]
@neoancient 
Exactly as Hammer describes, although I may have misunderstood how this works (although the fix does work properly for MekHQ).

**Comment by neoancient** [comment]
This is a MekHQ problem and should be fixed there. The Federated Commonwealth ceased to exist in 3057, though the Federated Suns portion continued to use the name for another ten years. Accordingly, FC is used to generated a combined Davion and Steiner military. As that didn't exist after 3057, the RAT generator correctly returns an empty table. If you want a Davion unit, the correct faction code is FS. The RAT Generator is not the problem.

**Comment by Windchild292** [comment]
I've thought a bunch on this, and I concur this isn't a proper fix. Will open the MOC.pm fix separately, then think about a pure MekHQ fix.

**Pull request closed without merging**
