### PR TITLE
Planetary conditions part 1 fixes sf.net ticket 4124

### PR DESCRIPTION
**Pull request by pheonixstorm**
This fixes several issues people were having with the weather, such as not knowing it had to be set manually. There are several other fixes as well

Visual Spotting: isAero was counting any aero as having the spotting modifiers for aero regardless of where they were. p221 Shows that only aero  at altitude 2-9 should have said modifiers while those below 2 are considered grounded and use the mech column and those at altitude 10 cannot visually spot.

Snow related movement: With the new fix in place this section was removed entirely as it was not being calculated correctly and was causing far higher penalties if the user set the temperature as well as a snow condition. All movement penalties are now calculated correctly based on wind and extreme temperatures.

Blowing Sand/Sleet: Mostly worked before except when shifting winds were in play. As written the affects of both should be lost if wind speed drops below moderate gale. This now works.

Conventional Infantry in Extreme Temps: The now die if not inside a building or transport

Part 2 Will include Hail, Black Ice, and possibly Lightning Storms but will not be done before stable.

This fixes sf.net ticket 4124 ice storm problems

### CODE REVIEW

**Comment by arlith** [comment]
Does #428 also get fixed with this PR?

**Comment by pheonixstorm** [comment]
No, needs a ruling from CGL to see if it qualifies for minimum movement since cold weather reduces the amount of movement a vehicle has

> For vehicles, for each 10 degrees C (or fraction thereof) higher than 50 degrees, reduce their Cruising speed by 1 Movement Point. For every 10 degrees C (or fraction thereof) less than –30 degrees, reduce their Cruising speed by 1 Movement Point. Recalculate Flanking speed based on the new Cruising speed.

I want to say that this would be the same as if a vehicle took multiple motive hits that reduced cruise speed to 0 in which case they don't get minimum movement but it really needs a clarification. If VampireSeraphin hasn't posted a question yet I will as I also want to know about infantry regarding this line of text:

> unless they are XCT troops (see p. 351), in which case they ignore such movement restrictions.

**Comment by pheonixstorm** [comment]
I take back what I said. 

After rereading it I think the issue is that VS is thinking the cause of the move penalty is the Snow Terrain in which case there is no bug, just a misunderstanding of how the weather works.

Overall movement penalties work as they are supposed to, and heat bonus/penalty for extreme temperatures also works now. Issue 428 can be closed.

**Comment by HammerGS** [comment]
Per a conversation with Arlith we are going to merge this.  It can receive additional testing this Dev cycle.

**Pull request merged**
