### PR TITLE
Thumper and Sniper weapons swapped with one another on various units and Mechs #6056

### PR DESCRIPTION
**Pull request by DM0000**
swapped Thumper and Sniper to their correct place
Screenshot 2024-10-03 101011
Screenshot 2024-10-03 100949

### CODE REVIEW

**Review by IllianiCBT — APPROVED** [review]
Approved, but how on earth did this get switched. xD

**Comment by pavelbraginskiy** [comment]
Github likes it when you put the words Closes #6056 in the PR description or a comment so that merging the PR automatically closes the issue.

**Comment by DM0000** [comment]
OK will add them

**Comment by Sleet01** [comment]
> Approved, but how on earth did this get switched. xD

Looks like it was in the process of replacing magic strings with constants:
https://github.com/DM0000/megamek/commit/167f06796b4de526867fc56ea0f9cc5e96ce9912

I would point out that having the constants, however incorrect, probably made fixing this issue a lot simpler :D

**Pull request merged**
